### ISSUE TITLE
_maybe_ update manifest versions

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/spec-bioimage-io#101]
I'm not sure there is a distinction here between spec and manifest spec version? For simplicity, I'd suggest to follow the same version numbers here and add the same versions as for the spec

https://github.com/bioimage-io/spec-bioimage-io/blob/a227af48b93b9777cddbec73d310145ed9642cb1/bioimageio/spec/raw_nodes.py#L23

**Comment by FynnBe** [comment]
yes there is a difference. @oeway  requested that we try not to bump the manifest version all that much and keep it independent of the model version. The manifest version could be considered equal to the general bioimage.io RDF version

**Comment by k-dominik** [comment]
hey @FynnBe , thank you very much for clearing that up! I adjusted the manifest version in our repo accordingly.

**Comment by FynnBe** [comment]
Just stumbled over this again and would really prefer @k-dominik proposal for a unified format version.

**Comment by constantinpape** [comment]
+1 for having one unified version for manifest, rdf and model rdf.

**Comment by FynnBe** [comment]
we keep separate format versions (see https://github.com/bioimage-io/spec-bioimage-io/issues/140#issuecomment-868667884)
