### ISSUE TITLE
Remove rf model and pickle weight format

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#104]
When moving the python spec repo over here we also moved the rf pickle model and "pickle" sneakily became an official weight format. I think we should completely remove this to avoid any confusion around it.
But let's wait with this till all the pending PRs are properly merged.

cc @FynnBe

**Comment by FynnBe** [comment]
yes, let the dust settle a bit and get rid of it then. 
todo:
 - [ ] add pytorch (and other) specs and use them in the tests instead of the rf model

**Comment by constantinpape** [comment]
I think once #157 is merged all remainders of the pickle format are gone.
