### ISSUE TITLE
futher improvements

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#105]
todos from https://github.com/bioimage-io/spec-bioimage-io/issues/97#issuecomment-859533766_
- [x] reactivate ci for tests (potentially with #103)
- [x] clean up `schema.Model` base class `schema.RDF` (mostly just move around fields) (common format version or not?)
- [x] CLI to verify models and manifest for specific versions (and not just the latest)
- [ ]  add more example specs here

**Comment by FynnBe** [comment]
another remaining problem: full auto conversion for documentation:

converting an invalid input (e.g. a url) to a local md file requires the whole package, not just the yaml content
not a problem for 'validate-spec' (<- should be renamed 'validate-model'.?), which takes a model.yaml path, but a problem for 'validate-bioimageio-manifest' (should be renamed 'validate-manifest'?)
- [ ] rename cli commands
- [ ] python packager to create package from yaml url
- [ ] write out deprecated documentation content to generated .md file (currently only saved unser `config` to pass validation

**Comment by constantinpape** [comment]
>     * clean up `schema.Model` base class `schema.RDF` (mostly just move around fields) (common format version or not?)

I think `schema.RDF` should rather be removed (or auto-generated from the jsonschema if possible), see https://github.com/bioimage-io/spec-bioimage-io/issues/107#issuecomment-859797703

**Comment by FynnBe** [comment]
to clarify: for now schema.RDF is the base calss of schema.Model, but is not used on its own and could be merged to schema.Model. But let's discuss further in #107 on how to progress...

**Comment by oeway** [comment]
@FynnBe Is this outdated already?
