### ISSUE TITLE
Generate docs from json schema

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#110]
Hi @FynnBe I am thinking maybe we can load the RDF json schema and generate a doc?

**Comment by FynnBe** [comment]
It is really easy to specify it in marshmallow and then generated the jsonschema and the docs just like we do with the model spec... 
we are discussing this in #107 (and #101 shows some opinions in favor of unifying the format version... )

**Comment by oeway** [comment]
I thought we can just load the jsonschema into `marshmallow` and generate the docs the same way, no?

**Comment by FynnBe** [comment]
not that I know, I don't see a way to load jsonschema into marshmallow. And, as there is always a way (writing it ourselves), even then I would prefer to have all the spec stuff follow the same pattern. would make life easier I think

**Comment by oeway** [comment]
OK, let's do it in marshmallow then, I will implement it in github actions to make sure we generate the docs automatically.

**Comment by oeway** [comment]
@FynnBe when you work on this, could you also try to enable [the CI command that generate json schema](https://github.com/bioimage-io/spec-bioimage-io/blob/7c70d8cfa9a97f44f0c60c43aaf54fe5e856e7ac/.github/workflows/build.yml#L45-L46)? I had some issue with it.
