### ISSUE TITLE
Provide spec compliant example yaml files

### ISSUE THREAD

**Issue by maweigert** [bioimage-io/spec-bioimage-io#111]
I think it would be nice to provide some spec compliant yaml files for different version of the format in the main repo. This way, it would be easier to debug validation errors  in custom specs that get created

**Comment by constantinpape** [comment]
Yes, we will work on this once the tests are running again, see #103 and we have removed the pickle related things from the spec, see #104 (this was just introduced for testing purposes and should not be part of the spec).
Initially, I think we should move two models here (and bring them up-to-date with the most recent spec):
- [Model with torch, torchscript, onnx weights](https://github.com/bioimage-io/pytorch-bioimage-io/blob/master/specs/models/unet2d_nuclei_broad/UNet2DNucleiBroad.model.yaml)
- [Model with tensorflow, keras, tensorflow_js weights](https://raw.githubusercontent.com/deepimagej/models/master/fru-net_sev_segmentation/model.yaml).

**Comment by constantinpape** [comment]
I am reviving this issue. We do have one example model now, but it would be good to have some more to also have more example models for different tests. In particular, I would like to have:
1. a model with keras, tf and tf-js weights
2. a model with multiple input and output tensors
3. a model which produces an output tensor of different size

I can take care of 2 and 3, but we would need your help for 1, @esgomezm.

**Comment by constantinpape** [comment]
There are a lot of example models now here: https://github.com/bioimage-io/spec-bioimage-io/tree/main/example_specs/models
