### ISSUE TITLE
Example UNet2DNucleiBroad spec fails to validate on 0.3.2

### ISSUE THREAD

**Issue by maweigert** [bioimage-io/spec-bioimage-io#112]
The [example](https://github.com/bioimage-io/pytorch-bioimage-io/blob/master/specs/models/unet2d_nuclei_broad/UNet2DNucleiBroad.model.yaml) currently fails to validate:

```
python -m bioimageio.spec verify-spec UNet2DNucleiBroad.model.yaml

{'authors': {0: {'_schema': ['Invalid input type.']},
             1: {'_schema': ['Invalid input type.']}},
 'weights': defaultdict(<class 'dict'>,
                        {'pytorch_state_dict': {'value': {'authors': {0: {'_schema': ['Invalid '
                                                                                      'input '
                                                                                      'type.']}}}}})}

```

**Comment by constantinpape** [comment]
This is due to the change in authors from `List[str]` to `List[Dict[str, str]]`.
Now the author field should look like this `[{"name": "My Name", "affiliation": "My Affiiliation", "orcid": "0000"}]`.
Where orcid and affiliation are optional. Note that this should work if you allow for conversion, but I guess this is not possible via the CLI yet, cc @FynnBe.

We will update this model when moving the example models, see #111.

**Comment by FynnBe** [comment]
it is possible, if you run
```>>>python -m bioimageio.spec verify-spec --auto-convert UNet2DNucleiBroad.model.yaml
successfully verified model UNet2DNucleiBroad.model.yaml
```
it works

**Comment by maweigert** [comment]
Ah, yes `--auto-convert` works, thanks! Maybe making this a default or mentioning it in the [Readme](https://github.com/bioimage-io/spec-bioimage-io#usage) makes sense...

**Comment by FynnBe** [comment]
Yes, it should be the default! Probably without jumping over minor format versions, e.g. `0.3.0` should be auto converted to `0.3.2` and validated, but `0.1.0` should be validated as `0.1.0` (highest `0.1`).

**Comment by maweigert** [comment]
Yes, that would make sense. On the other hand, it might be that auto converting might not be possible for version in the future (e.g. when introducing new functionality) and then one would probably like to validate the spec 'as is'...

**Comment by FynnBe** [comment]
yes, but patch version increments should never provide new functionality. Already changes like enforcing stricter requirements on the `license`. should have been a minor version increment, rather than a patch...

**Comment by maweigert** [comment]
Yes, that sounds good!
