### ISSUE TITLE
stardist integration

### ISSUE THREAD

**Issue by maweigert** [bioimage-io/spec-bioimage-io#113]
As per our discussion today, this is just to gather the current state of stardist integation (so will be updated from my side)

* Current PR in stardist: https://github.com/stardist/stardist/pull/149
* Example model (0.3.2. spec compliant):
[stardist_test_v0.3.2.zip](https://github.com/bioimage-io/spec-bioimage-io/files/6641452/stardist_test_v0.3.2.zip)

**Comment by constantinpape** [comment]
closed in favor of https://github.com/stardist/stardist/pull/171
