### ISSUE TITLE
Move 0.3.2 tag

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#114]
I think the 0.3.2 release was made pre-maturely and we need to move it due to:
- It did not have CI and the tests actually did not pass due to remaining issues in the spec, see #103 
- Parts of the python functionality did not work yet and are still not fully working, see #108 
- The validator uses marshmallow to validate the rdf instead of jsonschema, which will make all current rdfs fail, see #107. (Note that we are discussing switching to marshmallow as the reference for the rdf as well, BUT that requires a minor version bump.) (Also it' fine to validate with marshmallow, but we need to make sure that we are compliant with the current rdf spec.)

**Comment by FynnBe** [comment]
sorry, for I may have been the one with the trigger happy mouse on that release button 🙄

**Comment by constantinpape** [comment]
> sorry, for I may have been the one with the trigger happy mouse on that release button roll_eyes

No worries. I think we were all eager to get this one out...

**Comment by constantinpape** [comment]
I found some additional bugs #118, #117 that should be fixed before the release.
Any chance you could fix this soon, @FynnBe?

**Comment by constantinpape** [comment]
> Luckily these might be material for discussions and explanations (and documentation) rather than fixes...

Yes, this is resolved now. (Though I think that #118 is very confusing design, but I can work around it, see #119).
What's still to do before moving the tag:
- Update the validator so that the current rdfs pass (we should do it in marshmallow directly, given that we decided to also have the reference rdf spec there)
- Discuss and fix the issue with "model.yaml", see https://github.com/bioimage-io/spec-bioimage-io/pull/119#discussion_r651812626

**Comment by FynnBe** [comment]
> Update the validator so that the current rdfs pass (we should do it in marshmallow directly, given that we decided to also have the reference rdf spec there)

I'll take a look at that tomorrow.

**Comment by constantinpape** [comment]
> > Update the validator so that the current rdfs pass (we should do it in marshmallow directly, given that we decided to also have the reference rdf spec there)
> 
> I'll take a look at that tomorrow.

@FynnBe have we implemented this yet? It would be good to go ahead with the release before pushing anything to conda.

**Comment by FynnBe** [comment]
> @FynnBe have we implemented this yet? It would be good to go ahead with the release before pushing anything to conda.

almost ready to go: https://github.com/bioimage-io/spec-bioimage-io/pull/125
