### ISSUE TITLE
Serializing a raw_nodes.Model obtained via load_model fails

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#117]
When I load a raw_nodes.Model via `load_model`, serialization fails.
Minimal example (needs a valid model folder):
```python
import bioimageio.spec as spec
model = spec.load_model("/path/to/mode.yaml", root="/path/to")
spec.schema.Model().dump(model)
```
Fails with 
```
ImportedSource(factory=<class 'user_imports.5e008e787272408180a19fd72b83134b.UNet2d'>) has unexpected type <class 'bioimageio.spec.shared.nodes.ImportedSource'>
```

This issue does not occur if the `raw_nodes.Model` is obtained via the constructor.

**Comment by constantinpape** [comment]
Just for some context, I encountered this here: https://github.com/bioimage-io/spec-bioimage-io/pull/119/files#diff-1a29404c0d5393c60282c9b3a32ac3a68a41a9e4bd5b1339288d8a8cc133b454R429-R432

**Comment by FynnBe** [comment]
you should be using `load_raw_model`. The ("resolved") model has urls downloaded, etc. Also `source` is not the reference anymore, but  a `ImportedSource` node that  is and has a callable:
https://github.com/bioimage-io/spec-bioimage-io/blob/afff3a45a4e214d76b072f61dc6ef4c68a46054e/bioimageio/spec/shared/nodes.py#L7-L11

we might want to call `nodes` `resolved_nodes` instead to make the difference more explicit...

**Comment by FynnBe** [comment]
so
```python
import bioimageio.spec as spec
model = spec.load_raw_model("/path/to/mode.yaml", root="/path/to")
spec.schema.Model().dump(model)
```

should work

**Comment by constantinpape** [comment]
Hmm, I see. I really don't like these many layers of abstraction, this is so much unnecessary complexity...
Anyway, this fixes the issue.
