### ISSUE TITLE
Serialization of raw_nodes.Model writes out all missing fields with some default

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#118]
Serializing a `raw_nodes.Model` writes out the default values for all fields, also the ones not passed to the `raw_nodes.Model` constructor.
```python
import bioimageio.spec as spec
model = spec.raw_nodes.Model(...)  # create the model with some missing args

# round trip for validation
ser = spec.schema.Model().dump(model)
model = spec.schema.Model().load(ser)
ser = spec.schema.Model().dump(model)

# write to yaml
with open("model.yaml", "w") as f:
  spec.utils.yaml.dump(ser, f)
```
The resulting "model.yaml" will contain all fields with defaults (mostly `null` or empty lists). They should not be written at all.

**Comment by FynnBe** [comment]
After loading a model from a yaml file optional fields are filled with `None` or another appropriate 'empty' value like empty list or dict.
The reasoning is that users of the bioimageio.spec parser and validation should not need to know about the special 'missing' value and that certain missing fields are equivalent to those default values, thus your produced "model.yaml" is exactly equivalent after loading it again. 
This is desired behavor to make it easier to work with the parsed model and acknowledges that there is no logic difference between writing a model.yaml with e.g.
```yaml
...
cite: []
```
or leaving out the `cite` field altogether.

The choice of 'missing' values in the raw nodes allows us to specify meaningful default values only in one place (the schema), thus leaving out an optional field in raw nodes or in a model.yaml always leads to the same default value. This is why creating raw_nodes 'manually' is somewhat of an illegal move and needs a round trip to set the correct defaults.

**Comment by constantinpape** [comment]
Ok, I see. This makes using the raw_nodes very awkward, because they are different after validation / serialization and the state that comes back is very "non-intuitive", e.g. all weights have an entry for "opset version" although this only makes sense for onnx.
This also prevents using the library for things like "read the model yaml, add or update some fields and serialize it again".

Anyway, I can work around this for by writing a function that just removes all empty fields before serialization.

**Comment by constantinpape** [comment]
I have added a workaround in #119

**Comment by FynnBe** [comment]
let's use this space to dicsuss possible improvements or if we want to keep it this way (and find another approach without workarounds)...

**Comment by FynnBe** [comment]
>  e.g. all weights have an entry for "opset version" although this only makes sense for onnx.

This can be changed by adding specific WeightEntry raw_nodes/schema.

> This also prevents using the library for things like "read the model yaml, add or update some fields and serialize it again".

I see. I thought it is acceptable to fill in implicit default values explicitly on a round trip. The two are equivalent, so I don't see a big problem...

> Anyway, I can work around this for by writing a function that just removes all empty fields before serialization.

However, if we do not want implicit defaults turning into explicit ones we can simply set the defaults for optional fields in the schema to "missing" (or set 'required' to False, as 'missing' is the default for missing values (it's from marshmallow)). 
To avoid having to deal with two "None/missing" values in consumer software the defaults for missing values could be set when converting from raw_nodes to nodes instead. I really think that 'missing' should not make it's way into consumer software.

summary:
- set defaults in schema
  pro: 
    - defaults are available during validation
    - can be used to make implicit defaults explicit
    - can help to avoid diverging default values across consumer software (e.g. through round trip in packager)
  contra:
    - rount-trip changes 'unchanged' fields (by making implicit defaults explicit)
- set defaults in nodes
  - contra:
    - validation gets slightly more involved due to presence of 'missing' values
  - pro:
    - round trip does not change anything; clean deserialize/serialize ops

- no defaults
  contra:
    - writing valid 'empty' values in the yaml (null, [], {}) is different from leaving them out. 
    - clutters code with additional missing checks: `if value is None or value is missing`

**Comment by constantinpape** [comment]
> I see. I thought it is acceptable to fill in implicit default values explicitly on a round trip. The two are equivalent, so I don't see a big problem...

Fundementally, I don't see any reason for having these defaults at all. I don't see where they are useful, because having `None`, `[]`, `{}` does not provide useful information and just obfuscates whether this was put in by the model producer (for whatever reason) or whether it was added by the round-trip.
Do we really on having these default values anywhere? I think it would be much cleaner to either have fields missing (if they are allowed to be optional) or to just don't have them. It's then the consumers responsibility to deal with missing values (either using `.get` with default values when working with the dict view or `hasattr` when working with the dataclass view).

**Comment by FynnBe** [comment]
alright, no defaults then.

> hasattr when working with the dataclass view

dataclasses will have the 'missing' value then (they are not AttrDicts). if the dict view is just loading the serialzed yaml `.get` is an option, but if the dict es generated from the dataclasses it too will haven 'missing' values.
I think the guaranteed existence of keys is a good feature and avoids `.get("key_with_typo", ETERNAL_DEFAULT)` kinds of situations...

**Comment by constantinpape** [comment]
> dataclasses will have the 'missing' value then (they are not AttrDicts). if the dict view is just loading the serialzed yaml `.get` is an option, but if the dict es generated from the dataclasses it too will haven 'missing' values.

That's also fine. Should just be documented somewhere.
