### ISSUE TITLE
add ci-check / pre-commit hook for "passthrough" modules

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/spec-bioimage-io#126]
Background: we have multiple spec versions in this repo, which is awesome. In order to have the latest one available from `bioimageio.spec` directly, we have introduced a script that generates pseudo modules that link to the _current_ spec (atm this is `v0_3`). 

#122 introduced this additional step that would be necessary either when:
* we decide to move to the next spec version (`v0_4`),
* a modules is added or removed to/from the _current_ one (`v0_3`),
* the `__init__` of the _current_ one is changed.

the script (`scripts/generate_passthrough_models.py`) has a `check` subcommand, that currently checks that all modules in the _current_ spec have autogenerated modules in `bioimage.spec`.

It would be very useful to have a pre-commit hook for this, and also CI integration (see @FynnBe's comment [here](https://github.com/bioimage-io/spec-bioimage-io/pull/122#pullrequestreview-686222716)).

**Comment by FynnBe** [comment]
implemented in #139
