### ISSUE TITLE
make "passthrough" module check more correct :)

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/spec-bioimage-io#127]
the script (`scripts/generate_passthrough_models.py`) currently:
1. removes previously autogenerated modules from `bioimageio.spec`,
2. adds new modules in `bioimageio.spec` with links to the _current_ version, and
3. replaces _some_ contents in `bioimageio/spec/__init__.py`.

the `check` subcommand currently only checks for correctness of (2).

The check should also make sure `__init__.py` is enriched with the right content.

**Comment by FynnBe** [comment]
as a pre-commit hook this check could be performed by simply running the generation (it would then "fail" due to changed files). Would that solve this and is there a CI analog?

**Comment by FynnBe** [comment]
a pre-commit hook for this in in place and generate_version_submodule_imports has been improved
