### ISSUE TITLE
Add tiling flag to inputs

### ISSUE THREAD

**Issue by frauzufall** [bioimage-io/spec-bioimage-io#13]
A model consumer could be able to tile an input first and run the model prediction on all tiles - the basic example is one input image, one output image of the same dimensions. 

With n inputs and n outputs, This is not trivial anymore. An output already has a reference to an input which is great. With an additional tag indicating if an input can be tiled, the consumer could tile all inputs with this flag in the same ratio.

**Comment by frauzufall** [comment]
if we want to do this, it would make also sense to move the `reference_input` one level up from `shape`

**Comment by constantinpape** [comment]
We implicitly assume that tiling is always ok. But I see the point that this is not always the case, esp. when we are not dealing with image to image networks, so making this more explicit is a good idea.

Somewhat related to this topic: the shape specification for `outputs` can have the key `halo`, to specify which parts of the prediction to cut away. This is currently not documented, will fix this soon.

**Comment by FynnBe** [comment]
we have the `concatenable` flag (per input axis) to indicate if tiling along an axis is supported.
