### ISSUE TITLE
Generate json for the supported weight formats

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#130]
As we discussed during our last meeting, it would be great if we have can get a list of meta data about our supported formats.

I propose that we generate a `weight_formats_spec.json` file from the CI:
```json
{
  "consumers": {
     "deepimagej": {
       "name": "DeepImageJ",
       "icon": "....",
       ....
     }
      ...
  },
  "weight_formats": {
    "keras_hdf5": {
       "name": "Keras HDF5",
       "description": "Weight formats for models generated from Keras in HDF5 format",
       "consumers": ["imjoy", "deepimagej"]
    }
    ...
  }
}
```
@FynnBe could you also take a look at this?

**Comment by oeway** [comment]
I made a weights formats spec:
https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/weight_formats_spec.json

**Comment by FynnBe** [comment]
where is the code that generated it?

**Comment by oeway** [comment]
I wrote it by hand ;) the packager now use it on bioimage.io

There are two parts, the consumers we need to make a list, then fetch the detailed information from: https://github.com/bioimage-io/bioimage-io-models/blob/gh-pages/manifest.bioimage.io.json

For the formats, we may need to construct it by hand, I would perhaps read from a source json file with all the hand configured settings, then automatically expand it into the full version and place it under gh-pages branch. Any better idea?

**Comment by FynnBe** [comment]
> There are two parts, the consumers we need to make a list, then fetch the detailed information from: https://github.com/bioimage-io/bioimage-io-models/blob/gh-pages/manifest.bioimage.io.json

Why don't we add 'supported_weight_formats' to an application RDF (and maybe a `generic_consumer` flag to filter out specialized applications? Or we add RDF `type: consumer`?). Then discover all applications through [manifest.bioimage.io.json](https://github.com/bioimage-io/bioimage-io-models/blob/gh-pages/manifest.bioimage.io.json)  and create the weight formats overview?

This would allow application/consumer maintainers to directly 'sign up' for a weights format.

Also (eventually) the resulted weight formats overview should indicate if tests fail or pass for each consumer respectively...

**Comment by oeway** [comment]
It's a good idea to use RDF for describing the consumers, but we don't really need an additinal type, the application is already covers consumer software. Maybe we just need to add supported formats to the 'config' of the existing applications. We can also use that to sign up new formats.

**Comment by oeway** [comment]
One downside though, if some consumer decided to change an existing format, and that might cause issue for other consumer who use that, and we cannot easily prevent that. For now I would prefer a centralized approach to define new formats. Anyone who want to signup new formats need to send PR to the spec repo.

**Comment by FynnBe** [comment]
It would be great to validate the weight formats an application signs up for, though, no?

**Comment by FynnBe** [comment]
> One downside though, if some consumer decided to change an existing format, and that might cause issue for other consumer who use that, and we cannot easily prevent that. For now I would prefer a centralized approach to define new formats. Anyone who want to signup new formats need to send PR to the spec repo.

That's another good reason to keep the weight formats themselves centralized and validatable...

**Comment by FynnBe** [comment]
I'll start with a manual mapping of {consumer: [supported weight formats]}, but I would prefer to incorporate this into the application spec soon...

**Comment by oeway** [comment]
Why not get it from the application RDF already? I think don't need a dedicated spec for application at the moment, we can just go for the generic config field. Can you add that already to the Ilastik application config? I can change the compilation script to verify whether a configured formats exists.

Then we only need a weights definition here.

**Comment by FynnBe** [comment]
Actually we could avoid the 'supported_weights_formats' field if we would just check every weights entry of every model with every application (given that we have full dynamic tests)... 
then we have a 'supported by' table for every weight format of every model...

**Comment by FynnBe** [comment]
But why not add `supported_weights_formats` to the RDF (for `type: application` only/in a derived "Application RDF")?
Otherwise we enforce rules onto the `config` field or

**Comment by oeway** [comment]
Well, we can, but it’s might be better to have a explicit list, because
that’s a property of the application which should not depend on the models
it linked to. An application can support a new weight format even though
there is no model use that yet.

**Comment by FynnBe** [comment]
But adding `supported_weights_formats` to the (Application) RDF is an explicit list.  And this explicit list could of course contain a new weight format that no model uses yet as long as the validator knows this weight format. But adding a new weight format will always need a PR here to adapt the validator anyhow.

**Comment by FynnBe** [comment]
I'll make a draft PR to show you what I mean...

**Comment by oeway** [comment]
> But why not add `supported_weights_formats` to the RDF (for `type: application` only/in a derived "Application RDF")?
> 
> Otherwise we enforce rules onto the `config` field or
> 
> 
> 
> I suppose we can make it "official" later on as well and use 'config' for now... it seems like we'll end up doing that anyway though... 

I would prefer that we test the idea with config and then upgrade it later to a spec. Define spec before actually testing it often result in much less stable spec. It is fine at the beginning, but we should really try to avoid it as we have more users.

I would rather focus on the model RDF spec and generic RDF spec at the moment, branching out for other RDF types is not necessary at the moment and are likely complicate the development and maintenance.

But don't get me wrong, we do need to make things more standardize, but let's take it easy and test out ideas before upgrading to a spec.

**Comment by FynnBe** [comment]
alright, but we'll make it official in 0.4.0 (or 0.3.3 👀 ) 🚀 👍

**Comment by FynnBe** [comment]
```yaml
config:  {supported_weights_formats: ["wf1", "wf2"]}
```
it is for now... (with 3 's')

**Comment by oeway** [comment]
> ```yaml
> config:  {supported_weights_formats: ["wf1", "wf2"]}
> ```
> 
> it is for now... (with 3 's')

Looks good! Can you then compille it from the `manifest.bioimage.io.json` and generate the `weight_formats_spec.json` in the current format? Just to be clear, I can potentially do this dynamically in the packager, but this will result in downloading the entire `manifest.bioimage.io.json` everytime in the packager.

> alright, but we'll make it official in 0.4.0 (or 0.3.3 👀 ) 

I would leave it in `config` until we sort out other RDF types, there are datasets, and the new workflows may also need special keys that need to be taken into account.

**Comment by FynnBe** [comment]
> Just to be clear, I can potentially do this dynamically in the packager, but this will result in downloading the entire manifest.bioimage.io.json everytime in the packager.

> Also note that 0.4.0 is the model RDF version, the changes we are making here won't affect anything but the website and the packager.

sure, I just wanted to indicate that I would like to make this official rather sooner than later. also note that https://github.com/bioimage-io/spec-bioimage-io/pull/125 unifies the general and the model RDF format versions (to the model one)

>Looks good! Can you then compille it from the manifest.bioimage.io.json and generate the weight_formats_spec.json in the current format? 

will do, do you need the 'consumers' section in the model format as well or is that redundant?

**Comment by oeway** [comment]
> also note that #125 unifies the general and the model RDF format versions (to the model one)

Let's discuss that here: https://github.com/bioimage-io/spec-bioimage-io/issues/140

> will do, do you need the 'consumers' section in the model format as well or is that redundant?

Thanks! Yes, I will need that too.

**Comment by oeway** [comment]
@FynnBe To make the packager working, I had to add this lines in the CI: https://github.com/bioimage-io/spec-bioimage-io/blob/2eb5a4630c8bd2a374aa0c20d440a4219898bbf0/.github/workflows/build.yml#L72-L73
Please remove that when you can generate that file.

**Comment by oeway** [comment]
@FynnBe @constantinpape  Noticed another thing, when a model contains multiple formats that are supported by the same consumer, for example, [this model](https://bioimage.io/#/?id=10.5072%2Fzenodo.865618) contains two formats that are supported by ilastik, I am thinking that maybe we can make the `supported_weight_formats` ordered by priority. So we only propose to download the first matched format and consider that as the preferred format for the consumer. What  do you think?

**Comment by FynnBe** [comment]
Yes, although for download we might want to prefer formats that are the most cross-compatible, like onnx, no?
Regardless of what we offer as download, ordered priority for weights formats makes sense 👍

**Comment by oeway** [comment]
This one is fixed, closing now.
