### ISSUE TITLE
source spdx_licenses from somwehere else

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/spec-bioimage-io#131]
Currently, the pypi package `spdx-license-list` is used as a source for valid license identifiers. [That package](https://gitlab.com/uniqx/spdx-license-list) is deprecated (also we'd need to package it's license :o when making our binaries available). As far as I can see we are using the license _keys_ only. I guess we could create a python file containing either just a list, or the full dictionary from [here](https://github.com/spdx/license-list-data/blob/master/json/licenses.json), slapping the license (according to [this](https://github.com/spdx/license-list-data/blob/master/accessingLicenses.md) this should be  CC-BY-3.0) on it and lose the dependency?

**Comment by FynnBe** [comment]
will be solved in #132
