### ISSUE TITLE
FileNotFoundError licenses.json

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#137]
@k-dominik Is this related to the recent change in the license?

https://github.com/imjoy-team/bioimage-io-models/runs/2889305580#step:5:27

**Comment by k-dominik** [comment]
Hey @oeway, thx for pointing it out! I didn't notice the deployment failing. I noticed it with the conda recipe, too. There I added a `Manifest.in`. I'll check if I can fix the one-liner instead (after all it is only a single data file currently - don't want to create a new file just to include it.)
https://github.com/bioimage-io/spec-bioimage-io/blob/ea3f212585ec4d012e1ee8f38ebe9b3277a150a6/setup.py#L38
