### ISSUE TITLE
Discussion for the the generic RDF version vs model RDF version

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#140]
@FynnBe mentioned that in https://github.com/bioimage-io/spec-bioimage-io/pull/125 we are unifying the versions of generic RDF and model RDF, and I think it might be better to discuss that before we do that.

The generic RDF is much more stable than the model spec, I am not sure we should make then the same version. It would make a lot of sense if these are sibling components that depend on each other, but here the generic RDF is the parent of the model RDF. IMO, changes in the child RDF will causing the parent RDF to upgrade its version is not a good idea. 

Another reason is that we are using the generic RDF in the website, but the model RDF is mostly in a python package.  If we unifying the RDF versions, any change in the python package will likely need to  mean we need to change the website, in the future it will also trigger other child RDF to change versions.  It would be fine if we can provide backward-compatibility guarantee, but since we don't, I would rather leave the generic RDF alone. Only triggers version changes when the generic RDF changes, not the other way around.

**Comment by FynnBe** [comment]
the idea of unifying the format versions was discussed previously here https://github.com/bioimage-io/spec-bioimage-io/issues/101

I think a single formt version simplifies:
 - validating it
 - writing any bioimage.io RDF as a developer
 - moving fields from the general RDF to specialized RDFs

If the general RDF does not change from one version to another the website does not need to adapt. The website should not validate the format versions and may assume the latest version. We might want to add in auto-convert for all RDFs in order to ease maintenance...

**Comment by oeway** [comment]
> the idea of unifying the format versions was discussed previously here https://github.com/bioimage-io/spec-bioimage-io/issues/101

Oh, it seems I missed the discussion there.

> If the general RDF does not change from one version to another the website does not need to adapt. 

Well, that's not true, if we bump the version of generic RDF it means new RDF generated by developers may use that new version which the website don't understand. 

> We might want to add in auto-convert for all RDFs in order to ease maintenance... 

We can do that if we use our previous way of rendering the website RDFs in a single json file. However, since we decided to use zenodo for indexing all the items, the conversion can only be done in javascript,  this means the website needs to understand all the new versions--even if they never changed. For this, I would suggest we decouple the two.

Unified versions make sense for many cases, but here, I think it's really introduce a lot of complexity, and it's bad to tightly couple the website implementation to the python validator.

**Comment by FynnBe** [comment]
>> If the general RDF does not change from one version to another the website does not need to adapt.
>
> Well, that's not true, if we bump the version of generic RDF it means new RDF generated by developers may use that new version which the website don't understand.

why would the website not understand a new RDF if its fields haven't changed? (Does it check for the format version?) The moment we release a new RDF version the website should be ready to take it.

>>We might want to add in auto-convert for all RDFs in order to ease maintenance...
>
>We can do that if we use our previous way of rendering the website RDFs in a single json file. However, since we decided to use zenodo for indexing all the items, the conversion can only be done in javascript, this means the website needs to understand all the new versions[...]

I don't understand the problem of 'understanding' all versions if many versions don't differ, e.g. if 0.3.1 to 0.3.2 did not change the general RDF the conversion is trivial... 
The problem of multiple RDF versions that cannot be auto-converted to the newest is identical if we use different numbers for the general RDF.

**Comment by oeway** [comment]
> why would the website not understand a new RDF if its fields haven't changed? (Does it check for the format version?) The moment we release a new RDF version the website should be ready to take it.

The issue is that if we unify the version, it means the generic RDF may change even its content is not changed. Lets do an example: if we bump both generic RDF to 0.4.0, the website was built when we have 0.2.0, and it will only check if the version matches 0.2.0, now when it sees a new RDF with version 0.4.0, it doesn't know whether the new RDF file can work with 0.2.0. Because it may work or not depending on whether there is any actual changes in the format. This effectively make the format_version key useless for the website.

**Comment by oeway** [comment]
> The problem of multiple RDF versions that cannot be auto-converted to the newest is identical if we use different numbers for the general RDF.

Well I would not try to convert the generic RDF, because it's simple and only read by the website, the conversion and validation can be done in JS on the website. We only need to get the latest version of the generic RDF json scheme here.


The generic RDF are different also in a sense that we don't have consumer software that produce the generic RDF. Based on the new design with Zenodo, developer won't need to write any generic RDF.

**Comment by FynnBe** [comment]
> The issue is that if we unify the version, it means the generic RDF version may change even its content is not changed. Lets do an example: if we bump generic RDF to 0.4.0, the website was built when we have 0.2.0, and it will only check if the version matches 0.2.0, now when it sees a new RDF with version 0.4.0, it doesn't know whether the new RDF file can work with 0.2.0 or not. Because it may work or not depending on whether there is any actual changes in the format. This effectively make the format_version key useless for the website.

in this example wouldn't it be super easy to add 0.4.0 to the list of valid, understandable format versions? We don't release every week, and if the website can check for multiple versions, it'd be a trivial PR to add the new release that hasn't changed the general PR to that list.

**Comment by oeway** [comment]
> in this example wouldn't it be super easy to add 0.4.0 to the list of valid, understandable format versions? We don't release every week, and if the website can check for multiple versions, it'd be a trivial PR to add the new release that hasn't changed the general PR to that list.

Yes, it's trivial,  but also no, especially for long-term, it's not good to couple the two repos. Imagine this, every updates to the spec will depends two people make changes to two repos. I.e. if you now bump the version in Python package, it won't be easy for you to make the changes in the website repo. Even if we are willing to do it, considering that the generic RDF is likely much more stable than the model RDF and other child RDF, I just fell like the maintenance burden is much larger than the benefit it bring.

**Comment by FynnBe** [comment]
in today's bioimage.io meeting @oeway described the independence of the model rdf format from the general rdf formats and how the benefits  of independent format versions (see above) outweigh the drawbacks (see above).

https://github.com/bioimage-io/spec-bioimage-io/pull/125/commits/d2adc2e899c25f553170434e770297594160acbf separates the format versions in #125
