### ISSUE TITLE
Add links and upgrade authors in the generic RDF

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#143]
As discussed during the meeting (https://github.com/bioimage-io/bioimage.io/issues/28#issuecomment-869141291), we should add `links` and upgrade the `authors` format to synchronise with the model RDF.

**Comment by FynnBe** [comment]
RDF.links are already added 6341549240870fc0293e3568ff9fb4d01af1b62b

**Comment by oeway** [comment]
This is implemented already, @FynnBe please reopen if not.

**Comment by FynnBe** [comment]
in general RDF 0.2.0 (current) authors still can be a string or the new authors scheme with name, affiliation and orcid... I'd keep this open until we disallow the simple author strings in genral RDF 0.3.0 or later
