### ISSUE TITLE
Make the spec validator configurable

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#156]
In the [current implementation](https://github.com/bioimage-io/spec-bioimage-io/blob/cf9e737d9511995c1dce5c73fbd93fb6f3201f4e/bioimageio/spec/v0_3/raw_nodes.py#L28-L36), all the options (e.g. `framework`) in the spec is all hardcoded, including keys in the general RDF which are meat to be undefined (e.g. `type`).

It would be good that if we can separate the values (e.g. in a separate json config file), and keep the dry rules in the validator code. This means when we add a new type or framework, we don't need to change the source code or upgrade spec version.

**Comment by FynnBe** [comment]
But aren't valid values for specific fields part of the spec version? Adding or removing any would require a spec version bump, otherwise the released spec version could become inconsistent...

**Comment by oeway** [comment]
> But aren't valid values for specific fields part of the spec version? Adding or removing any would require a spec version bump, otherwise the released spec version could become inconsistent...

I think that's the current behavior, but I think it would worth some more discussion to see what's the best option. 

We can separate the dicussions into two parts: 

1) regarding the implement, Maybe it's a personal favor, I don't like hardcoded stuff in the code in general, so even if we want to bump version for any change to the spec, I would keep the code dry and take out the options store it in either a module or a json file. The advantage is that when we want to add new types, new definiton, we don't touch the code, but only the config. I would vote for json because this will allow the website/packager to pull those information directly. 

2) regarding whether we should bump the spec version for any change in the added or removed options, we need to keep in mind that every new version we create, we make all our previous model looks older (even if the change does not affect the consumer software at all), and it create confusion for the developer since they won't know it's a breaking change or simply because we now defined a new preprocessing type which doesn't affect anything. So I would propose we see the frameworks/pre/postprocessing options differently, we take out them from the spec, but treat them as "implmentations" of the validator. This means if we add or remove stuff, we keep the spec version but change the validator version. This will make the spec version more stable, and more meaningful for the developers. A spec version change means we added or removed some keys, not because of we now support a new framework `mxnet` which we should have added in the beginning.

Happy to see what you think.

**Comment by FynnBe** [comment]
> 1. regarding the implement, [...]

IMHO the "spec code" is marshmallow and our whole spec-bioimage-io uses that marshmallow library to specify our specific BioImage.IO RDFs. We discussed at length how to do this and tried json schema besides marshmallow. We decided to stick with marshmallow as it allows more precise validation compared to json schema (and the generation of json schema). Of course the code base can be improved, there is room for interesting discussions and improvements. None of which seem urgent at this point, though.

> 2 a regarding whether we should bump the spec version for any change [...]

this is what we can use the patch part of the format versions for. small changes that do not invalidate existing resources. major and minor version can be very stable with non-invasive patch changes. Any addition of framework/pre-/postprocessing could contribute to a patch bump. And yes, we should strive for this!

**Comment by oeway** [comment]
> IMHO the "spec code" is marshmallow and our whole spec-bioimage-io uses that marshmallow library to specify our specific BioImage.IO RDFs. We discussed at length how to do this and tried json schema besides marshmallow.

To be clear, I am not suggestion json schema, I propose that we extract those configurable options (e.g. framework) and store it in a json file. Same as the SPDX license which are stored in a json file, so one can easily add and remove license without touching the code, I think we should do the same for those options. It's rather a way to make it easier for the those who don't actively work with the library. This should even be in a contributor guideline, e.g. if you want to add a new type of framework, edit this json file. 

This would be a good way to enable more collaborations on it, otherwise, even for me, I won't be confident to change the code to just add some options.

> Of course the code base can be improved, there is room for interesting discussions and improvements. None of which seem urgent at this point, though.

Right, the easier we make it to maintain by multiple people (or even the external users) the better.

Sure this is not urgent, but it's nice to discuss this. And in general don't take everything I posed here as urgent. In most case I just want to record it down. But it's easily enough to extract those configurable values and store it in a separate file, I might do it later.

> this is what we can use the patch part of the format versions for. small changes that do not invalidate existing resources. major and minor version can be very stable with non-invasive patch changes. Any addition of framework/pre-/postprocessing could contribute to a patch bump. And yes, we should strive for this!

Good!
