### ISSUE TITLE
The packager is failing due to wrong supported_weights_format file

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#163]
A recent change make it producing the wrong supported weights format file: https://github.com/bioimage-io/spec-bioimage-io/blob/6e0051a8697c5c03074ed42e8f0671522646d5bf/weight_formats_spec.json#L129-L172

And it cause the pacakger to fail on bioimage.io.

**Comment by oeway** [comment]
@FynnBe Could you look into this, I just manually restored the file to keep the website functioning.

**Comment by FynnBe** [comment]
I just pushed a fix to main: https://github.com/bioimage-io/spec-bioimage-io/commit/134de15f36341ae18646ae965f2458c7c898d471

**Comment by FynnBe** [comment]
that seems to have done it...

**Comment by oeway** [comment]
Thank you! @FynnBe
