### ISSUE TITLE
How to do tiling as a consumer

### ISSUE THREAD

**Issue by frauzufall** [bioimage-io/spec-bioimage-io#17]
We discussed tiling today at the Hackathon (related to #13).

It would probably make sense to have similar strategies in Python and Java.
 
## Which input can be tiled?
- an input can be tiled if there is a dimension with `step > 0 `

## How to run the model on a subset of an input?
- output node `halo` describes the margin around a tile
- a subset has to have size `min + n*step`
- a subset has to be at position ? (we discussed that there might be a limitation here that is not clear how it is defined yet)

**Comment by esgomezm** [comment]
If it helps, in DeepImageJ we thought about facing it as follows:
- If the task is image classification, then there is no tiling (this could be extended to not image to image network)
- else we always do the tiling of the entire image by calculating the optimal value of n that covers the entire image, taking into account the `halo` and the `min + n*step` condition.

**Comment by constantinpape** [comment]
Closed in favor of #227
