### ISSUE TITLE
Make model RDF a valid general RDF

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#177]
As we discussed already, it would be nice to let any model RDF to be a valid general RDF. To implement that, I believe the missing thing is to allow additional keys in the general RDF, is that correct? @FynnBe

**Comment by FynnBe** [comment]
Yes, should that be added to general RDF 0.2.0?

**Comment by oeway** [comment]
> Yes, should that be added to (/corrected in) general RDF 0.2.0?

Technically, it would be ok to implement that to 0.2.0, we didn't say that we don't allow additional keys.

**Comment by FynnBe** [comment]
alright, as it is very uninvasive I'll just add it to 0.2.0 then
