### ISSUE TITLE
load raw for remote RDFs

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#201]
I would appreciate some input on the following problem:

local paths in remote rdf.yaml files are changed to urls when loading them as 'raw'. this is to avoid invalid, non-existing local file paths and allows to load the 'non-raw' resolved version from them.
The change to urls is done after validation, but may result in an invalid raw resource as urls are not allowed for all fields... in combination with the non-raw load it is valid again, but as a raw node it is invalid. 
- leave as "supported internally only" -> warn when loading a remote RDF as 'raw'?
- Lift restriction to local paths (WOULD CHANGE RDF SPEC!)
- don't do the 'remote url transformation' and ...
    - leave the non-existing local paths and remeber the original source of the RDF to resolve them.
    - even on 'load raw' download any local paths. (unnecessary download, especially for weight files (would download all of them if they are specified as local files!)
  
How I stumbled on this now:
atm we are including an 'original rdf' file in packages (purely for reference) which atm would actually contain the urls instead of local paths (so much for 'original'). Right now this fails due to asserting a local relative path when serializing fields like `documentation` which is expected to be a local relative path and not a URL.

**Comment by FynnBe** [comment]
for now I decided to warn about 'raw remote RDFs'

**Comment by constantinpape** [comment]
I don't really understand this issue. The warning solution sounds good for now; if you want more feedback we would need to discuss this in person.

**Comment by FynnBe** [comment]
if warning sounds good to you we can leave it at that 👍
