### ISSUE TITLE
Invalid type annotation

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#221]
https://github.com/bioimage-io/spec-bioimage-io/blob/main/bioimageio/spec/shared/common.py#L64

**Comment by constantinpape** [comment]
This causes one of the github actions to fail.

**Comment by FynnBe** [comment]
fixed by https://github.com/bioimage-io/spec-bioimage-io/commit/d541c3346f41769143dcd8de1c13c59cbe9b76ed
