### ISSUE TITLE
NameError: name 'YAML' is not defined

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/spec-bioimage-io#224]
Hi there, 

I get the following error when running the spec checker:
https://github.com/deepimagej/models/runs/3242600205

The error comes from this line in the code:
https://github.com/bioimage-io/spec-bioimage-io/blob/d541c3346f41769143dcd8de1c13c59cbe9b76ed/bioimageio/spec/shared/common.py#L62

**Comment by constantinpape** [comment]
This will be fixed once https://github.com/bioimage-io/spec-bioimage-io/pull/223 is available on pip/conda.
You can also add ruamel.yaml to the dependencies to fix the issue rn.
