### ISSUE TITLE
Error: No such command 'verify-bioimageio-manifest'.

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/spec-bioimage-io#225]
Is this function replaced by another one or should I just remove it from the checker?

```
pip install git+https://github.com/bioimage-io/spec-bioimage-io.git
python -m bioimageio.spec verify-bioimageio-manifest --auto-convert manifest.bioimage.io.yaml
```

**Comment by constantinpape** [comment]
This is replaced by [bioimageio validate](https://github.com/bioimage-io/spec-bioimage-io/blob/main/bioimageio/spec/__main__.py#L38):
```
bioimageio validate manifest.bioimage.yaml --update-format
```

**Comment by constantinpape** [comment]
(we should update the readme to document these commands)

**Comment by constantinpape** [comment]
I have updated the readme.
