### ISSUE TITLE
Enable ImplicitOutputShape with scale, offset and reference tensor for inputs

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#234]
Currently, the `ImplicitOutputShape` with `scale`, `offset` and `reference` is only valid for output tensors.
However, this setting also makes sense for input tensors, e.g. when we have two input tensors and one is half the (spatial) size of the other.

**Comment by FynnBe** [comment]
very good point. So should we change it to `ImplicitShape` and use it for inputs alike?

**Comment by constantinpape** [comment]
> very good point. So should we change it to `ImplicitShape` and use it for inputs alike?

Yes, sounds good.

**Comment by constantinpape** [comment]
@FynnBe should we make a 0.3.3 release for this? I think this is something that would really not hurt any existing model and it would be nice to have a new release that is not 0.3.2postX.

**Comment by FynnBe** [comment]
yes, let's do that!

**Comment by FynnBe** [comment]
some questions for implementation details:
- [ ] when using `ImplicitShape` for both inputs and outputs, we should change `reference_input` as well, thus `reference_tensor` might be a better name?
- [ ] `reference_tensor` can point to inputs or outputs. It might be useful to forbid name duplicates across all inputs/outputs?
- [ ] strictly speaking this would break compatibility to 0.3.2, unless we implement an automatic renaming scheme that for example prepends 'in_' and 'out_' to the given names for anything <= 0.3.2, but this is very much an edge case and I would be in favor of either ignoring this or publishing it as 0.4 (the changes planned for 0.4 could move to 0.5)

**Comment by constantinpape** [comment]
> some questions for implementation details:

I agree, it should be called `reference_tensor`, we should demand unique names across inputs / outputs (I think this is a good change in any case) and we should target 0.4 instead, given that this is a breaking change.

Let's prepare the PR with this in mind and then discuss the 0.4 release in the next Friday meeting.

**Comment by FynnBe** [comment]
as I already started  implementing this, it would be great to have some changes in 0.3.3 (like changing the name `reference_input` to `reference_tensor` and then add the (breaking) changes where we use this for inputs in 0.4?

**Comment by constantinpape** [comment]
> as I already started implementing this, it would be great to have some changes in 0.3.3 (like changing the name `reference_input` to `reference_tensor` and then add the (breaking) changes where we use this for inputs in 0.4?

And then you would have a converter from 0.3.2 to 0.3.3 that renames `reference_input` to `reference_tensor`? That works for me.

**Comment by constantinpape** [comment]
This is suppoted in 0.4 now. (Not sure if it's fully working in core, but that's a different question)

**Comment by oeway** [comment]
@FynnBe Does this mean we should also support implicitShape for input tensors? However, this changes is not reflected in the docs of `inputs`.

**Comment by FynnBe** [comment]
> @FynnBe Does this mean we should also support implicitShape for input tensors? However, this changes is not reflected in the docs of `inputs`.

I suppose we should. This has been prepared a little with minor changes, but it is not yet implemented in spec...
