### ISSUE TITLE
Question about PostProcessing: `scale_range`

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#238]
> `reference_tensor` tensor name to compute the percentiles from. Default: The tensor itself. If `mode`==`per_dataset` this needs to be the name of an input tensor.

 -- https://github.com/bioimage-io/spec-bioimage-io/blob/main/supported_formats_and_operations.md

This leaves it unclear what `reference_tensor` may be if `mode` == `per_sample `

**Comment by FynnBe** [comment]
for `per_sample` we could theoretically also allow other output tensors as reference.

**Comment by FynnBe** [comment]
same question arises for  postprocessing `scale_mean_variance` btw

**Comment by constantinpape** [comment]
> This leaves it unclear what `reference_tensor` may be if `mode` == `per_sample `

In that case it can be both an input or output tensor (because it's clear that this refers to the tensor from the same batch).

> same question arises for postprocessing `scale_mean_variance` btw

Same solution as for `scale_range`

> for `per_sample` we could theoretically also allow other output tensors as reference.

Yes. Also, this implies that tensor names should be unique, but we want to change that in 0.4.0 anyways.

**Comment by FynnBe** [comment]
alright, thanks for clearing that up! 👍
