### ISSUE TITLE
Test inputs/outputs for multiple tensors

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#241]
Hi, I am dealing with a densenet model with two outputs (N*1024 dimension features and N* 28 dimension probability), in this case how should I prepare the test inputs and test outputs npy file? In this case, I will need to save the two output tensors as separate npy files, right? then how should I specify them in the `test_outputs` to avoid confusion with multiple instances of tests?

```
test_inputs:
 - {input1: ./input1.npy}
 - {input1: ./input2.npy}

test_outputs:
 - {features: ./features1.npy, prob: ./prob1.npy}
 -  {features: ./features2.npy, prob: ./prob2.npy}
```

The issue here is that npy format only support a single ndarray, alternatively, we can use npz (a zip file with a set of npy files), which support multiple arrays with names. 

> The .npz file format is a zipped archive of files named after the variables they contain. The archive is compressed with zipfile.ZIP_DEFLATED and each file in the archive contains one variable in .npy format. For a description of the .npy format, see numpy.lib.format.

Reference: https://numpy.org/doc/stable/reference/generated/numpy.lib.format.html#module-numpy.lib.format

We can potentially switch to npz format, basically it's going to be always a zip of npy files, the keys should match the inputs/outputs tensor name. One advantage of this is that it's will also compress the test array which can potentially save a lot of space.

What do you think?

**Comment by FynnBe** [comment]
Last time we discussed this problem we had agreed that `test_inputs` and `test_outputs` cover a single test case only

> List of URIs to test inputs as described in inputs for a single test case. Supported file formats/extensions: '.npy'

-- https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/model_spec_latest.md

If we want to cover multiple test cases we should considering renaming the field, e.g. to `test_cases` to emphasize this change.
Then something like this might make the added support of multiple test cases more explicit:
```yaml
test_cases:
  - inputs: test_inputs.npz  # e.g. containing ipt1 and ipt2
    outputs: {out1: test_output1.npy, out2: test_output2.npy}
  - ... # second test case    
```

**Comment by oeway** [comment]
OK, almost forgot what we have discussed ;) 
I think limit to only one test case make sense, maybe we don't need to expand it to more, at least for now. Then, we should describe this in the spec!

**Comment by oeway** [comment]
Oops, sorry, accidentally committed to main branch directly ;(

**Comment by constantinpape** [comment]
No worries, the change in doc looks good!
