### ISSUE TITLE
Verify a yaml string

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#242]
@FynnBe I am looking for a way to verify a yaml string in the bioengine, I confirm that I can import bioimageio.spec, could you provide a short script for me to verify a yaml string?

**Comment by FynnBe** [comment]
We didn't expect that use case actually, but I made a PR to support it: https://github.com/bioimage-io/spec-bioimage-io/pull/243

This is because calling the validate command with a yaml string is somewhere in between calling it on a file (url or path) and calling it with a dictionary (what you would get if you load a file with yaml). 

Calling it with a yaml string obviously still has the ruamel.yaml dependency. If you want to avoid it, you need to pass the string beforehand and call the validate function with a dictionary instead. 

```python
from bioimageio.spec.commands import validate

from ruamel.yaml import YAML

yaml = YAML(typ="safe")

# preload yaml 
source = yaml.load("spec_file_or_string")
# no yaml dependency below, unless source is not a dict, but instead:
# source = "existing_spec_source_path"  # or as os.PathLike, e.g. pathlib.Path
# or
# source = "https_spec_source_url"
# or  with PR #243
# source= "name: 'yaml string model'"

code = validate(source)
if code == 0:
    print("valid")
else:
    print("invalid")
```

**Comment by FynnBe** [comment]
note that pyyaml uses YAML 1.1 (not YAML 1.2 like ruamel.yaml) and pyyaml would also require `yaml.safe_load("yaml_string")` to load a string instead of a file, but we should not use pyyaml as valid specs need to be written in YAML 1.2 so in python we should stick to ruamel.yaml.

**Comment by constantinpape** [comment]
> If you want to avoid it, you need to pass the string beforehand and call the validate function with a dictionary instead.

I think that would be the better option in the browser:
- load the dict representation with yaml in js
- pass the dict to python (can be json encoded)
- validate dict in python

This way you don't need the yaml dependency.

**Comment by oeway** [comment]
Both works for me, a string or a dictionary, go ahead and implement any you think the best.
Thank you!

**Comment by FynnBe** [comment]
dictionary has been implemented first and #243 now adds support for the yaml strings. In conjuntion with pyodide you should opt for the dictionary as @constantinpape sketched aboved, which already works now.

**Comment by oeway** [comment]
Ok, great!

@FynnBe In your example use the valid function, how do I get the detailed error message if it's not valid?

**Comment by FynnBe** [comment]
With #246 commands.validate returns a dictionary with detailed error messages (which might be nested in lists and dicts)
