### ISSUE TITLE
offset in ImplicitOutputShape is cast to int

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#280]
This is an issue because we calculate the output shape as `out_shape = in_shape * scale + offset * 2`, so we need to allow for fractional output values in case the target value for `offset * 2` is an odd number.

**Comment by FynnBe** [comment]
related question: for such uneven case, how would one determine the relative position of output wrt input?

**Comment by constantinpape** [comment]
> related question: for such uneven case, how would one determine the relative position of output wrt input?
> (we might want to ignore this one for now and just leave it to the judgement of any consumer software)

I think this case mostly comes up for the channel axes in order to specify the number of output channels as `scale=0, offset=n_channels/2`. So I would ignore the issue for now.
