### ISSUE TITLE
Finalizing `v0.4`

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#296]
- remove `language` and `framework` fields (not useful)
- move `source` and `kwargs` to pytorch weight format
- require that tensor names are unique across input AND output tensors

**Comment by constantinpape** [comment]
- for tensorflow models the input output tensor names must agree with the names of the input/output tensor in the graph in order to be compatible with Java (this was true beforehand already, but not fully documented.)

**Comment by FynnBe** [comment]
last time we discussed the unique tensor names we also intended adding:
 - model inputs (like outputs) may be defined by `scale`ing and `offset`ing a `reference_tensor` (#236)

**Comment by FynnBe** [comment]
@constantinpape could we finalize the halo description (#278) as well?

**Comment by constantinpape** [comment]
> last time we discussed the unique tensor names we also intended adding:
> 
>     * model inputs (like outputs) may be defined by `scale`ing and `offset`ing a `reference_tensor` (

Yes, good point, we should include that.

**Comment by constantinpape** [comment]
@FynnBe @oeway  I forgot something else we discussed on friday: being strict about the SPDX licences
I think we should discuss this with the others first though, so I would not make this change just yet.

**Comment by FynnBe** [comment]
right, let's bring it up tomorrow morning 👍 I'll prepare it as a separate PR

**Comment by oeway** [comment]
Ok, added SPDX to the spreadsheet

**Comment by FynnBe** [comment]
in the weights entry for `pytorch_state_dict` (as for any weights entry) the field `source` already exists (pointing at the source of the weight file. 
I therefore propose to call the the `source` field we want to move in there `code` instead to avoid the name collision.

**Comment by FynnBe** [comment]
or should we go with `source_code`?

**Comment by constantinpape** [comment]
done
