### ISSUE TITLE
Add optional field icon to model RDF (general RDF has it)?

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#298]
The optional `icon` field can be used on the website to customize the RDF icon (some of the consumers specify their icon: https://bioimage.io/#/?type=application, e.g. ilastik and deepimagej)

The documentation of it is somewhat lacking for RDF 0.2: https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/rdf_spec_0_2.md#icon

Atm, if an icon is not given a random animal is chosen to be displayed as icon the website.

As this field is optional any model RDF without it is still a valid RDF, so this is not an issue at all. I suppose at some point the idea that models should be able to customize their icons came up...

**Comment by oeway** [comment]
Yes, I think we should add that, any valid string should do it. For example, an image url or a emoji string.

**Comment by constantinpape** [comment]
Sounds good, as long as it's optional I don't see any issues with this.

**Comment by tomburke-rse** [comment]
Same for me. I don't see a problem with that.

**Comment by FynnBe** [comment]
thanks for the quick feedback, implemented the changes in #297
