### ISSUE TITLE
bioimageio.validate fails for the manifest.bioimage.io.yaml files

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#324]
it fails for (at least) the first two entries in https://github.com/bioimage-io/collection-bioimage-io/blob/main/rdf.yaml#L30-L48:

https://github.com/HenriquesLab/ZeroCostDL4Mic: 
```
Error in manifest.bioimage.io.yaml:
("expected loaded resource to be a dictionary, but got type <class 'str'>: "
 'manifest.bioimage.io.yaml')
```

https://github.com/deepimagej/models/blob/master/manifest.bioimage.io.yaml
```
Error in manifest.bioimage.io...:
"'outputs'"
```

**Comment by FynnBe** [comment]
> it fails for (at least) the first two entries in https://github.com/bioimage-io/collection-bioimage-io/blob/main/rdf.yaml#L30-L48:

this is not a valid collection... not sure if we want to update it here or in the spec to make it valid... I'll look into the collection repo first as we planned some more changes there and make sure that the collection specified there will be valid either way....

**Comment by constantinpape** [comment]
> this is not a valid collection... not sure if we want to update it here or in the spec to make it valid... I'll look into the collection repo first as we planned some more changes there and make sure that the collection specified there will be valid either way....

I am not sure what's the best strategy, but the current state where rendering from a non-valid collection just works is very confusing because it's unclear how to fix it and the error messages are not helpful.

**Comment by FynnBe** [comment]
yes, but I suppose we have a limited amount of collection rdfs in use atm anyway... still, this needs a fix either way
