### ISSUE TITLE
General RDF 0.2.1

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#326]
I propose a few minor changes to the current general RDF 0.2.0:
- add `maintainers` field (like model 0.4)
- add `email` and `github_user` to `authors` entries (like model 0.4)

**Comment by FynnBe** [comment]
(maintainers would be optional, thus this would just be a patch bump)

**Comment by constantinpape** [comment]
Fine with me.

**Comment by FynnBe** [comment]
implemented in #328
