### ISSUE TITLE
Don't throw warning for non-OSI compliant licenses

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#329]
I don't think this is a good idea, as the OSI compliant licenses do not support any CC-BY license, which to the best of my knowledge is the best category of licenses for distributing data in a FAIR way. 
(I am refering to e.g. `ValidationWarning: license: CC-BY-NC-4.0 (Creative Commons Attribution Non Commercial 4.0 International) is not approved by OSI`).

**Comment by oeway** [comment]
I agree, I think we should reserve these warnings until we have a clear plan on what to recommend.

**Comment by FynnBe** [comment]
since https://github.com/bioimage-io/spec-bioimage-io/commit/3d7fab3daa321bdf533e4566b6221dcbdc3199af we don't throw this warning anymore

**Comment by FynnBe** [comment]
please reopen if issue persists on current main branch

**Comment by oeway** [comment]
It might because I didn't upgrade the version on the website.
