### ISSUE TITLE
Move `dependencies` field into `weights`?

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#341]
Currently we expect one dependency field to specify an environment suitable for all specified weights, while what might be more appropriate is to define dependencies for each weight entry.

**Comment by tomburke-rse** [comment]
That is a sensible move I think. Having TF, Keras and Pytorch (and dependencies) in one environment is prone to case problems and might also just not be possible at all.
In Favor.

**Comment by oeway** [comment]
Sounds good to me, and this should have been migrated together with 'source'. Just to clarify, we only need this dependency field for weights formats that reads source code, right? So I would make it optional.

**Comment by constantinpape** [comment]
> Currently we expect one dependency field to specify an environment suitable for all specified weights, while what might be more appropriate is to define dependencies for each weight entry.

Sounds good

**Comment by FynnBe** [comment]
> Sounds good to me, and this should have been migrated together with 'source'. Just to clarify, we only need this dependency field for weights formats that reads source code, right? So I would make it optional.

That's a good point. Given that we have TF version and onnx version, I think we just move it to pytorch_state_dict (and maybe think about adding a torchscript version.... 
An argument againg optional dependencies for tf and other weights is that the specified tf version could disaggree with dependencies.
Is anyone using the `dependencies` field for any weights other than pytorch? If not I'll move them to pytorch_state_dict (just like we moved source).

**Comment by constantinpape** [comment]
> I think we just move it to pytorch_state_dict (and maybe think about adding a torchscript version....

Keras might also need it, because keras weights also serialize and load the full model and may need custom code.

Otherwise this sounds good, but we should double check with @esgomezm if this has any implications for deepIJ before going ahead.

**Comment by esgomezm** [comment]
Hi! We don't use dependencies, that for sure. But I need to check if changing fields would affect deepIJ because the new version is ready and changing it would imply test everything again

**Comment by oeway** [comment]
@esgomezm We should be able to simplify the testing by put a bit more work to the deepimagej CI, Carlos made it works for one model, we can scale it for all your models.

**Comment by esgomezm** [comment]
Sure, but this is not for the testing. DeepIJ fails reading the model if the format of the yaml is not the correct one. Although we don't read pytorch models, if there's a model with different weights in the yaml, and the specification of one of them is not as expected, it could output an error message. That's what I want to avoid.

**Comment by esgomezm** [comment]
Ok, so it seems it's not a big deal. You can go for it.

**Comment by FynnBe** [comment]
implemented for pytorch_state_dict in https://github.com/bioimage-io/spec-bioimage-io/pull/346

when we take a closer look at the keras weights we can add it there, too. We might want to split those keras weights into two distinct weight formats (weights only/whole model...)
