### ISSUE TITLE
Implement "load_resource_description" / "load_raw_resource_description" with weight type

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#351]
At some point we should implement passing a weight type argument to both functions (I no, one of them is in core) to enable just downloading the necessary weights and save bandwidth when loading model resourcces.
(Not high priority.)

**Comment by constantinpape** [comment]
Works for `load_resource_description` since https://github.com/bioimage-io/core-bioimage-io-python/pull/195.
Doesn't work for `load_raw_resource_description` yet.
@FynnBe if possible I think we should add it for `load_raw...` as well.

**Comment by FynnBe** [comment]
but `load_raw...` doesn't download any weights anyway? you want to preselect the weights anyway?

**Comment by constantinpape** [comment]
> but `load_raw...` doesn't download any weights anyway? you want to preselect the weights anyway?

Ok, makes sense. Let's skip implementing it for `load_raw...`
