### ISSUE TITLE
Timestamp should be a string

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#364]
Currently the spec defined `timestamp` as `Timestamp of the initial creation of this model in ISO 8601 format`. However, the type is `DateTime`, which is a bit confusing because `ISO 8601` is a standard for representing datetime, typically as a string. Meanwhile, in the example rdf files ([e.g.](https://github.com/bioimage-io/spec-bioimage-io/blob/dbbba34f90ab49426328f82da85176917549b1b7/example_specs/models/unet2d_fixed_shape/rdf.yaml#L40)) it's specified as a string.

I think we should fix the documentation and make sure the type of `timestamp` is a string representation of date in ISO 8601 format. Meanwhile, to make sure we have a consistent behavior for all the yaml parsers, it is recommended to add quotes to the value of `timestamp`. (This is because some parser treat date-like string differently depending on whether they are quoted or not)

**Comment by FynnBe** [comment]
this issue is somewhat outdated, I'm closing for now, noting that we accept both timestamp iso strings, as well as YAML timestamps following the YAML 1.2 spec.
