### ISSUE TITLE
Add pytorch and keras version fields

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#374]
Maybe we should also add (optional) pytorch or keras version fields to the corresponding weight formats. For keras this can def. be useful, and for pytorch we also have some incompatabilities between weights stored in different versions.

**Comment by FynnBe** [comment]
for Keras we currently have an optional `tensorflow_version` field (https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/weight_formats_spec_0_4.md). We decided for `from tensorflow import keras` as recommended (https://keras.io/guides/functional_api/), or is there a new problem with that that I'm not aware of?

**Comment by constantinpape** [comment]
Yes, you're right about keras. (I was thinking that we might need the keras versions for legacy models where `from tensorflow import keras` does not work; but I think that for these cases the developer then needs to specify the explicit dependency file).
But I think we can still add the optional pytorch version

**Comment by FynnBe** [comment]
to sum up the current plan:
For the dynamic test per weight format we use
 - the env specified or a default (per weight format)
 - overwrite (or add) weight specific libraries that have direct optional version keys (e.g. `pytorch_version`, `tensorflow_version`, `opset_version`)

I have one remaining concern: For pure tf/keras/onnx models the model should not have any additional dependencies other than the 'standard' ones.. why do we need `dependencies` here?
If this is only the case for special cases like one of the ways one can save a keras model (not storing the architecture, but only the weights) then maybe we should rather add a new weight format (e.g. `keras_separate_architecture`) and add `dependencies` just for that. I really haven't worked a significant amount with the non-pytorch weight formats though... so tell me why I'm wrong, please.

**Comment by constantinpape** [comment]
> I have one remaining concern: For pure tf/keras/onnx models the model should not have any additional dependencies other than the 'standard' ones.. why do we need `dependencies` here?

I think for the keras case it's often necessary to add more dependencies to enable loading the model. (The model needs to be recompiled in order to make sure it's a pure keras model, similar to `torch.save` / `torch.load` if you save the full model rather than the state dict) (This opens up some more questions about how this would be imported when loading the model, but we could think about this later.) I would like to avoid adding a new weight type for this.

Another important point: exact pinning of e.g. `tensorflow version` will not work. (I tried a bit and  the only reliable way is to do a range pin for e.g. `>=1.14,<1.15`). So if people really need a specific version they need to provide a dependency file with the exact pin (and then it's their responsibility that the dependency file is correct.)

**Comment by constantinpape** [comment]
This is done.
