### ISSUE TITLE
validate minimum shape produces a "valid" output after processing

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/spec-bioimage-io#392]
Parametrized input shape is currently defined as: `shape = min + k * step for k in {0, 1, ...}`
The output shape is defined as `shape = shape(input_tensor) * scale + 2 * offset` as well as `shape_after_crop = shape - 2 * halo`. 
As a tiling consumer software, one would _always_ remove halo. So, it is possible, that for some `k` the output shape could be `<=0` (for some dimensions), which I would say constitutes an invalid model. Could we enforce that the input shape has to be given such that the output after halo cropping is still a valid shape?

**Comment by constantinpape** [comment]
I agree that this should be checked. It might not be possible to check this statically though (which is implemented here), but rather only possible in the dynamic check (in https://github.com/bioimage-io/core-bioimage-io-python). But @FynnBe would know how to best do this.

**Comment by FynnBe** [comment]
we should be able to do this statically....
