### ISSUE TITLE
Docs for collection is gone

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#400]
@FynnBe It seems the markdown document for collection is missing from gh-pages: https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/collection_spec_latest.md

**Comment by FynnBe** [comment]
yes, sorry, just noticed that myself, had accidentally committed some commented some lines.. will be fixed in [299cc6f](https://github.com/bioimage-io/spec-bioimage-io/pull/401/commits/299cc6fa1ad4990e4335d40e0d463db4da2cc9a1) 
when https://github.com/bioimage-io/spec-bioimage-io/pull/401 is merged

**Comment by FynnBe** [comment]
all back...
