### ISSUE TITLE
Rethink the parent field

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#407]
We currently have this for the parent field:
```
parent (optional ModelParent) Parent model from which the trained weights of this model have been derived, e.g. by finetuning the weights of this model on a different dataset. For format changes of the same trained model checkpoint, see weights. ModelParent is a Dict with the following keys:

    sha256 (optional SHA256→String) Hash of the parent model RDF.
    uri (optional Union[URI→String | RelativeLocalPath→Path]) Url of another model available on bioimage.io or path to a local model in the bioimage.io specification. If it is a url, it needs to be a github url linking to the page containing the model (NOT the raw file).
```

This seems weird not to allow a bioimage.io id here; which would be more natural in our current spec.

**Comment by FynnBe** [comment]
agreed. Given that this is not heavily used yet I would just change it to bioimage.io (in model RDF 0.5) without any auto-conversion.

**Comment by constantinpape** [comment]
For now, let's avoid using the field and use `link` instead to indicate parent models.

**Comment by constantinpape** [comment]
I think that the current definition is actually ok, we should just update the description of `uri`:
```
 Url of another model available on bioimage.io or path to a local model in the bioimage.io specification. If it is a url, it needs to be a github url linking to the page containing the model (NOT the raw file).
```
Instead, we should say that this should preferably a bioimage.io id, but can also be a local filepath or a url.

**Comment by FynnBe** [comment]
should we drop `sha256` then? For the id's we guarantee some level of stability (maybe the name get's a typo fixed, etc..), so this is a hastle to keep the sha updated and for other URLs/relative Paths a reference might be enough without the sha as well? we haven't checked the parent source's sha so far anyway I think

**Comment by oeway** [comment]
Changing it to a resource id scoped under bioimageio make sense to me.

**Comment by FynnBe** [comment]
maybe keep URLs allowed allows to point to model parents outside of bioimage.io?

**Comment by oeway** [comment]
> maybe keeping URLs as an option allows to point to model parents outside of bioimage.io?

Yes, that would be good for now. Dropping stuff may break things so we need more careful consideration. And we can always drop stuff in a later step.

**Comment by FynnBe** [comment]
if we do drop the sha field now I would simplify the parent field just as `parent: uri/bioimageio_id` instead of `parent:uri:...` ok?

**Comment by oeway** [comment]
> if we do drop the sha field now I would simplify the parent field just as parent: uri/bioimageio_id instead of parent:uri:... ok?

But this is a breaking change, right? Droping the `uri`/`sha256` part will make the parsing harder, and we will need to do regex to determine the different cases right? I would take it easy and make the non-breaking change for now.

**Comment by FynnBe** [comment]
> But this is a breaking change, right? Droping the `uri`/`sha256` part will make the parsing harder, and we will need to do regex to determine the different cases right? I would take it easy and make the non-breaking change for now.

easily auto-convertible though, so from the spec side this wouldn't be a problem

**Comment by constantinpape** [comment]
First, I am in favor for dropping the `sha256` since we are not using it so far anyways and this will be very sensitive to fixing typos etc. (if this is easy for other consumers to change, see below).

> if we do drop the sha field now I would simplify the parent field just as `parent: uri/bioimageio_id` instead of `parent:uri:...` ok?

So to be very precises, your proposal would be to have
```yaml
parent: "some-bioimage-io-id"  # could also be a url or filepath
```
instead of 
```yaml
parent:
  uri: "..."
```

> easily auto-convertible though, so from the spec side this wouldn't be a problem

Yes, it's easy on our end, but we have to consider that there are also java consumers for who it might be a bigger change.
Would you need to update anything in deepimagej or bioimageio-java to support the changes discussed here, @esgomezm @carlosuc3m @tomburke-rse?

**Comment by FynnBe** [comment]
> So to be very precises, your proposal would be to have

Yes, exactly

**Comment by carlosuc3m** [comment]
If the changes are only on the parent field, the changes should not affect DeepImageJ

**Comment by FynnBe** [comment]
so more explicit: `parent:id` + `parent:uri` which should probably be exclusive (I would still drop the `sha256` field) sounds good to me, too @constantinpape , are you ok with that?

**Comment by oeway** [comment]
> so more explicit: parent:id + parent:uri which should probably be exclusive (I would still drop the sha256 field) sounds good to me, too @constantinpape , are you ok with that?

Making them exclusive sounds good to me, but still I don't see why you want to drop an optional field which maybe useful in the future. Keep in mind that dropping a field is a breaking change. For me, introducing such a breaking changes should always have a very strong reason to do it, and be done via a longer deprecation process even if we think no one is using it at the moment (we don't know, it's a public document which can be used by anyone without beyond our reach).

**Comment by constantinpape** [comment]
> so more explicit: `parent:id` + `parent:uri` which should probably be exclusive (I would still drop the `sha256` field) sounds good to me, too @constantinpape , are you ok with that?

Fine with me.

**Comment by FynnBe** [comment]
I'll kepp the `sha256` as well, but add a note that we don't use it atm

**Comment by oeway** [comment]
Thanks! @FynnBe

**Comment by esgomezm** [comment]
thank you Fynn!

**Comment by FynnBe** [comment]
thanks for all input!
