### ISSUE TITLE
Validate on bioimage.io broken

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#411]
It's not working because of missing requests:
![validate-bug](https://user-images.githubusercontent.com/4263537/156061062-74e2191a-0d64-4132-b802-6d0cc6872d93.png)

(posting it here because this is probably due to missing import guards)

**Comment by constantinpape** [comment]
And while we're at it, can we add a test for this?

**Comment by FynnBe** [comment]
the requests module is only required for the warnings, the test fails due to the unexpected "dependencies" field

**Comment by constantinpape** [comment]
Sorry, I didn't read the message carefully enough (and thought that all the stuff should be auto-updated, but that's not possible for the model I used.) I fixed it now.
