### ISSUE TITLE
validate imjoy plugins in collection

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#413]
In our collections are entries for applications that point to imjoy plugins:
```yaml
  - id: deepimagej
    source: https://raw.githubusercontent.com/deepimagej/models/master/src/deepimagej-app.imjoy.html
```
https://github.com/deepimagej/models/blob/49afaec2596d08dea3462cfe1ed02974ec0e68fa/manifest.bioimage.io.yaml#L55-L56

In the collection repo exists an imjoy plugin parser: https://github.com/bioimage-io/collection-bioimage-io/blob/7b3732cc1c830e3a6f4343826659e0f27f504d38/scripts/imjoy_plugin_parser.py

I propose that we move that one over here in order to be able to resolve BioEngine application RDFs specified in this manner. 
Furthermore I would change the script and save the .imjoy.hml link under `rdf_source` as in the collection as this is the field that gets resolved in order to create the collection entry. Other ordinary fields (like `source`) are merely updated accordingly.

I can implement all these changes and clean up our partner's collection RDFs, we (looking at you there @oeway , @constantinpape ) just need to agree on a sufficiently clean way to allow for proper validation.

**Comment by constantinpape** [comment]
> It might be cleaner if we put the resolve imjoy plugin function in some imjoy/bioengine repository and use this to populare the collection RDF in the partner resource repositories.

That sounds good to me, but I can't get a very informed opinion here, since the BioEngine is @oeway's domain.

**Comment by oeway** [comment]
But the bioengine files are not part of the spec, right? Not sure if we should move it to the spec repo. The `collection` spec also allow arbitrary RDF types, and if we change to something like this for example:
```
  - id: deepimagej
    type: application
    source: https://raw.githubusercontent.com/deepimagej/models/master/src/deepimagej-app.imjoy.html
```
Then we make it a fully valid RDF entry, and we only validate it as a general RDF (I would not go further and add the `application` spec for the moment).

Still, I think it make more sense to have the plugin parser in the collection repo considering the spec repo is exposed externally but the collection repo is more for internal use.

> I think I would prefer this separation of imjoy plugin development and its translation into an RDF...

Not sure if I understand this, but the plugin parser is solely responsible for parsing the fields in a plugin file so we don't need to write the RDF manually, there is no imjoy plugin development in there. 

Another way to see this is that we are already parsing the zenodo items in the collection repo (i.e. converting DOI to the zenodo RDF), with the ImJoy parser, we are basically doing the same -- we convert from a .imjoy.html file to an RDF.

**Comment by oeway** [comment]
On a second thought, would it make more sense to have an abstraction layer for RDF parser? We can do:
 1. Doi to RDF
 2. RDF file url to RDF
 3. BioEngine/ImJoy file to RDF
 4. Protobuf to RDF (for triton)
 5. Custom parser

**Comment by FynnBe** [comment]
> Still, I think it make more sense to have the plugin parser in the collection repo considering the spec repo is exposed externally but the collection repo is more for internal use.

the reason I am bringing this up now is invalidity of the partner collections that have application RDFs. 
They are just no valid at the moment as `id` + `source` is not a valid RDF (or collection entry). Making these entries valid is the current objective.


> Another way to see this is that we are already parsing the zenodo items in the collection repo (i.e. converting DOI to the zenodo RDF), with the ImJoy parser, we are basically doing the same -- we convert from a .imjoy.html file to an RDF.

The only zenodo specific part of this is the logic of resolving local files in the records, but the zenodo record already holds a valid rdf (one can download it and it is valid). the .imjoy.html files though are very different and need a specific parser (+ dependencies for that parser) and thus if imjoy changes its format the plugin parser needs an update (that's what I meant with imjoy development).

So this BioEngine/ImJoy <-> RDF parser is not part of the spec, thus should be elsewhere. The collection repo is not the correct place for it as the partner collection RDFs should be able to validate their collection independently of the central collection repository, which depends on those partner repos. Otherwise we introduce a loop in the dependency graph.

IMO the imjoy parser should live in an imjoy repository. partner repos can use it to add entries to their collection, then validate their collection with bioimageio.spec and in the collection repo we pull the resources together (from valid partner collections and zenodo).

**Comment by FynnBe** [comment]
it seems a bit overkill to create a dedicated bioimage-io/imjoy-parser repository, but on the other hand having a small tidy python package for this could be useful as all partner should use this parser...

**Comment by oeway** [comment]
@FynnBe Is the following a valid collection entry?

```yaml
- id: deepimagej
    type: application
    name: DeepImageJ
    description: DeepImageJ BioEngine App
    source: https://raw.githubusercontent.com/deepimagej/models/master/src/deepimagej-app.imjoy.html
```

If yes, I would go for this way. I don't see why any other repo besides the collection repo need to resolve the entry entirely. The entry can stay as a general RDF for other consumer or partner repo.

> IMO the imjoy parser should live in an imjoy repository. 

Well, not sure, it's also coupled with the RDF spec, the parser is wrote dedicated for converting to RDF, more specifically tailored to display it as a card on the website. Plus the ImJoy plugin format is stable and almost guaranteed to backward compatible.

Practically, even if we do that, say we publish a pip package just for that single file, we still need to keep track of the versions. So if ImJoy changes its format (although we won't change it), you still need to change something in the collection. The difference is that to change a version number or change something in the file.

In addition to that, although we use ImJoy plugin file, but these plugins are specifically made for BioImage.IO, there are specific tags for fields we will add only for BioImage.IO, and they won't make sense to run outside the website.

Honestly, I think it's a bit over engineering and we are just moving the same problem from one place to another, or split them into different places (which is worse for maintenance  IMO).

**Comment by FynnBe** [comment]
> Is the following a valid collection entry?

almost we additionally need `format_version` (which is otherwise taken from the collection, which may deviate from the general format version)
-- https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/rdf_spec_latest.md

But, very well, this is a neat solution and causes the least headaches; the manual overhead should be small, there are not going to be new applicaitons every week...

**Comment by FynnBe** [comment]
resolution:
we won't validate imjoy plugins specially, but instead expect collection entries to hold a valid RDF. For the website we will add optional fields with the imjoy plugin parser that will stay in the collection repo and will not be exposed at all.

**Comment by oeway** [comment]
> But, very well, this is a neat solution and causes the least headaches; the manual overhead should be small, there are not going to be new applicaitons every week...

Exactly!


> resolution: we won't validate imjoy plugins specially, but instead expect collection entries to hold a valid RDF. For the website we will add optional fields with the imjoy plugin parser that will stay in the collection repo and will not be exposed at all.

Great then! Thanks!
