### ISSUE TITLE
Resolve relative URL correctly

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#440]
Right now, for the deepimagej collections, all the cover images are broken, I think it's because we used the collection root path to resolve the relative cover url. While the correct way should be extracting the URL from the rdf_source url, then use that as a base url to generate the cover URL and other files.

@FynnBe

**Comment by FynnBe** [comment]
yes, I'm on it 👍

**Comment by FynnBe** [comment]
all cover images are now resolved correctly
