### ISSUE TITLE
Improve error message for partner validation

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#453]
I got an error: `"Expected dict type for loaded source, but got: <class 'str'>"` for the partner validation CI but no idea where does the error come from: https://github.com/bioimage-io/bioimage-io-resources/runs/6385884221?check_suite_focus=true#step:4:24

Edit: Same here: https://github.com/imjoy-team/bioimage-io-resources/runs/6385989752?check_suite_focus=true#step:4:24

cc @FynnBe

**Comment by FynnBe** [comment]
the file path is given as string. the file does not exist though so it is not recognized as a file path and instead loaded as a yaml string. the file name string loaded as yaml remains a string.... thus the 'loaded' rdf is a string now... 
I improved the error message in https://github.com/bioimage-io/spec-bioimage-io/pull/454
fixed the validation in the imjoy repo here: https://github.com/imjoy-team/bioimage-io-resources/pull/11
and fixed the validation in bioimage-io-resources here: https://github.com/bioimage-io/bioimage-io-resources/commit/5395274c1ac825c26ac035823b7c5eb1924b0957

**Comment by oeway** [comment]
> 

Got it! Thanks!
