### ISSUE TITLE
Slash in the name

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#462]
It looks like the validator in the uploader doesn't throw error when there is a slash in the model name.

**Comment by FynnBe** [comment]
any other symbols we shouldn't allow in the name?

**Comment by oeway** [comment]
> any other symbols we shouldn't allow in the name?

Cannot think of any other symbols, let's start with that?

**Comment by FynnBe** [comment]
in tensor names we keep allowing slashes?

**Comment by FynnBe** [comment]
.. and author names...
