### ISSUE TITLE
Is it possible to make the DL framework version of the weights compulsory?

### ISSUE THREAD

**Issue by carlosuc3m** [bioimage-io/spec-bioimage-io#464]
Hello I was wondering if making the field that contains the version of the Deep Learning framework for a weights file compulsory was possible. In that case, for every model we would know if it was trained, for example, with Pytorch 1.5 or 1.10. 

When we introduce Tensorflow 2, I think it is crucial that we know if the model was trained with tf1 or tf2. And also, I guess that at some point old pytorch models will start sharing the repo with newer ones, and their Pytorch versions might start being incompatible, so I think that knowing with which versions the models were trained it's key for ease of reproducibility.

In addition, in DeepIcy, we will only allow weights whose DL framework version is known to be executed, so it would increase a lot the number of models available in the software.

Regards,
Carlos

**Comment by constantinpape** [comment]
Overall I agree that it could make sense to make this mandatory.
But it would mean that we have to bump the spec version - and a lot of old models wouldn't be auto convertible (if they don't have the version info already). Also, there is some more logic involved here with the (optional) dependency file, where the framework version can also be restricted and which we currently treat as having higher precedence than the framework version given in the yaml.

So this would be a rather complex undertaking that in my opinion is a bit too disruptive right now.
