### ISSUE TITLE
allow _some_ form of forward compatibility

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/spec-bioimage-io#468]
this comes from an offline discussion with @FynnBe.

In the context of software that is distributed in _binary_ form to end users, it is possible, that some dependencies, e.g. `bioimageio.spec` move on - which in general is fine. There is, however, a problem with models generated in newer versions - they will not work with older versions of the library. Currently, in a situation where the client is e.g. `0.4.5`, but the model was generated with `0.4.6`, the client will error out when trying to load the model. Often the models don't use any feature _specific_ to this version, but were merely generated with it.

I know there's 0ver and all of that, but it would be really great to start giving _some_ guarantees about compatibility between versions. @FynnBe already pretty much nailed backwards compatibility (so far I didn't have problems with that). So doing some kind of forward compatibility, maybe for minor versions, would be pretty useful.

CC: @oeway @constantinpape @esgomezm

**Comment by FynnBe** [comment]
my suggestion here is to implement that on failure due to a future version we try to load the resource as the latest known version. generating a good error message would be important here to keep the attempt transparent...
