### ISSUE TITLE
Make cite optional for models

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#470]
Currently the `cite` field for the model RDF is a required field and it force to have a doi, which can be hard for unpublished models.  I think we should make it as an optional field so one can skip it. Note we already made the `cite` field in the general RDF as optional.

Also see https://github.com/bioimage-io/collection-bioimage-io/pull/473 (which has one error related to this.)

**Comment by constantinpape** [comment]
I agree, I think we should throw a warning if `cite` is missing.

**Comment by FynnBe** [comment]
there was a bug hiding the `url` field within a `CiteEntry`
currently `doi` or `url` have to be specified. 
We can still make `cite` opitonal of course...
