### ISSUE TITLE
don't download anything from the internet when importing top-level stuff

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/spec-bioimage-io#490]
currently doing

```Python
import bioimageio.spec
```

will result in the client making requests to

https://github.com/bioimage-io/spec-bioimage-io/blob/9ef423de7db2a2f587bcca261601ccdae73ab4da/bioimageio/spec/shared/_resolve_source.py#L510-L515

I would say this is a bit impolite. Also I would imagine that a lot of functionality of this package can be used without having access to `BIOIMAGEIO_SITE_CONFIG` and `BIOIMAGEIO_COLLECTION` (correct me if I'm wrong). I'm only a bit afraid that this constitutes a sneaky way of tracking usage of this library (at least it would be possible). Is this intended?

**Comment by FynnBe** [comment]
resolving the model nicknames like "impartial-shrimp" requires a request. With a bit time at hand one could make these requests lazily...
Alternatively we could maybe add this dynamic data statically to the python package and add a command to update the collection. I think this would be the best as it is reliable/fails fast and doesn't spam unintended requests. What do you think @k-dominik ?

**Comment by k-dominik** [comment]
Hi @FynnBe,

sorry for the late reply. For now we choose to delay imports in ilastik rather than resolving this issue. I guess for the behavior of this package I would first try to find out, whether there is _anything_ a developer would use this package for that doesn't require the information gained with these requests?

**Comment by FynnBe** [comment]
when loading a local model rdf or a remote one identified by it's rdf.yaml url the current collection does not need to be known to resolve an animal nickname....

Generating warnings for missing tag categories will--in the current implementation--always require to resolve the `BIOIMAGEIO_SITE_CONFIG_URL`. 

Having a version of these two files (site config and collection) added as static with a command to update should cover most applications.
updating the site config does not necessarily need to be included in such an update as we do not update the tag categories often and having them outdated only leads to outdated or missing warnings. However, if an update mechanism for resolving the animal names would be in place we might as well include a site config update...
