### ISSUE TITLE
Request to include pixel size/resolution in the spec

### ISSUE THREAD

**Issue by petebankhead** [bioimage-io/spec-bioimage-io#499]
The topic of including the requested pixel size (resolution) in the model spec came up at the recent HT hackathon.

I [wrote a little rant on Zulip](https://imagesc.zulipchat.com/#narrow/stream/368074-.5B2023-02.5D-Accessibility-of-deep-learning-models-from-Java/topic/Pixel.20size/near/326591243) about why I think it's important, and at @ctrueden's suggested wanted to include it here.

In summary:

1. It's extremely common in pathology (and potentially useful elsewhere) to train models from images from a variety of sources, often acquired using different scanners that use different pixel sizes. Rescaling images later to have a standardized pixel size is an effective way to reduce at least *one* source of variation, and have a model that can potentially generalize well.
2. It's also extremely common to train models that should be run at different resolutions for different purposes (e.g. 0.5µm/px for nucleus detection, 5µm/px for tumor recognition)

QuPath definitely needs resolution information, but other software does as well - e.g. see 
* https://github.com/kaczmarj/wsinfer/issues/68

Having the intended resolution as an optional entry in the spec would help avoid more reliance on custom configs.

**Comment by FynnBe** [comment]
we have discussed quite a bit already and this is the current proposal: #290
@petebankhead it would be great to get your feedback on that!

**Comment by petebankhead** [comment]
Sorry, hadn't seen that - I'll think some more, but first impression is that the approach looks good to me!

**Comment by FynnBe** [comment]
`unit` and `scale` were added to the axis descriptions in model 0.5
