### ISSUE TITLE
Json schemas of the specs 

### ISSUE THREAD

**Issue by ivan-ea** [bioimage-io/spec-bioimage-io#507]
I have a question about the json schema version of the spec of the different rdfs, such as the [model_spec_04](https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/model_spec_0_4.json).

Do these json schemas convey 100% of the information from the specifications, or are there any caveats?

**Comment by FynnBe** [comment]
there are a bunch of caveats: 
1. I'm not sure if all spec fields are somewhat correctly represented in the json schema (it's basically a draft that is not in use anywhere)
2. the validation is limited; the planned use is to generate a json form from the json schema.
3. it's not tested

the schemas are generated by https://github.com/bioimage-io/spec-bioimage-io/blob/main/scripts/generate_json_specs.py
