### ISSUE TITLE
Author's Name is required but accepts Empty String

### ISSUE THREAD

**Issue by mese79** [bioimage-io/spec-bioimage-io#512]
I've checked both in `schema` and `raw_nodes`, You can create an Author instance with an empty string for the name property which is a required one.
```python
from bioimageio.spec import rdf

a1 = rdf.raw_nodes.Author(name='')
print(a1)

author_schema = rdf.schema.Author()
valid = author_schema.validate({
    'name': '',
    'email': None,
    'affiliation': None,
    'github_user': None,
    'orcid': None,
})
print(valid)
```
This piece of code runs ok, but it should throw a validation error.  
The marshmallow recommends using the Length Validator (`marshmallow.validate.Length`) for handling empty strings.

**Comment by mese79** [comment]
Apparently, this is the case for every **`required` String** fields.  
One solution could be adding `Length` validation for each required string field with custom `min` and `max` parameters.  
Another solution would be creating a new field class like `NonEmptyString` and add proper validation there, and then subclass it where ever it is necessary.  
For a generic solution, a schema validation could be added to the `SharedBioImageIOSchema`. Then we can check all required string fields to have at least one character length.  
```python
class SharedBioImageIOSchema(...):
    ...
    @validates_schema
    def check_empty_required_str(self, data, **kwargs):
        for name, field in self.fields.items():
            value = data.get(name, None)
            if field.required and isinstance(field, fields.String):
                if value is not None and len(value) < 1:
                    raise ValidationError({field.name: 'Required string field must have length > 0'})
```

**Comment by FynnBe** [comment]
@mese79 thank you for this input!

I like refactoring the use of `fields.String`  into `fields.NonEmtpyString` a bit more I think. Although I don't think empty strings are meaningful anywhere in this project, this is more explicit.

**Comment by FynnBe** [comment]
Maybe we can simply add a `min_length` arg to `fields.String` with a non-zero default.

**Comment by mese79** [comment]
> Maybe we can simply add a `min_length` arg to `fields.String` with a non-zero default.

This is a good idea, as you said, empty string should not be allowed anywhere (`None` for optional and non-empty for `required`).  
We can add a validator to the `String` class to issue a validation error for an empty string all the time.

**Comment by mese79** [comment]
#514
