### ISSUE TITLE
Drop support for Python 3.7 and 3.8

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#515]
I am currently looking into simplifying bioimageio.spec to speed up further development, ease maintenance and make the code base more approachable to new developers. 
Doing this work I realized that I would really like to drop support of Python 3.7 (End-of-life 2023-06-27) and also drop support for Python 3.8 (End of life 2024-10), see https://devguide.python.org/versions/

What do you think about shifting to support and test Python 3.9, 3.10 and 3.11 instead of the current 3.7, 3.8, and 3.9 ?
(I have the release of bioimageio.spec 0.5 in mind for these changes where we also update the `axes` descriptions.)

Any strong opinions out there @constantinpape @oeway @esgomezm @carlosuc3m @k-dominik ?

**Comment by constantinpape** [comment]
No strong opinions from my side; we can drop 3.8 (and earlier) support.

**Comment by carlosuc3m** [comment]
No strong opinions from my side either

**Comment by k-dominik** [comment]
Hm... why drop 3.8?

**Comment by FynnBe** [comment]
> Hm... why drop 3.8?

Python 3.9 has been out for 2 years and 8 months, so rather why not drop 3.8 with it's EOL in a bit over a year.

Also I like mergin dicts with `|` and already using type hinting generics from standard collections already now avoids a lot of deprecation warnings in Python 3.9. 

So if no one has trouble switching to 3.9+ in the intermediate future for new features/development (the current releases are still available for Pyton 3.7+), it would be a pleasure to work with Python 3.9+ moving forward :-)

**Comment by k-dominik** [comment]
Makes sense. Your original comment didn't state any reasons, hence the question. So thanks for the clarification. I don't think we should blindly drop compatibility with arbitrary reasoning like EOL is in a year...

Don't get me wrong, I don't need python <39, but wouldn't `from __future__ import annotations` avoid the warnings and enable the functionality? :) pipe-unioning dicts is of course nice syntactic sugar :).

**Comment by oeway** [comment]
Hey, the triton python backend runtime is at 3.8, they might upgrade and there are ways to pack newer python versions but that will introduce extra workload for packaging, deploy and testing. I would appreciate if we keep 3.8 for a little longer.

**Comment by FynnBe** [comment]
What a shame, let's only drop 3.7 for now then!
