### ISSUE TITLE
Confusion because spec and core provide bioimageio CLI

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#516]
Issue reported by @esgomezm:
The validation command in the doc: https://github.com/bioimage-io/spec-bioimage-io#bioimageio-spec-validator does not work as expected.
This is because yaml is not included in the default installation (see discussions in this issue).
We should also somewhere add a recommendation to use `bioimageio.core` if one has access to  a full python installation, as this avoids many issues.

_Originally posted by @constantinpape in https://github.com/bioimage-io/spec-bioimage-io/issues/265#issuecomment-981641410_

**Comment by FynnBe** [comment]
I propose to remove the CLI from bioimageio.spec entirely to force Python users to validate with bioimageio.core which allows to validate much more thoroughly anyway.

**Comment by constantinpape** [comment]
I agree, let's remove the CLI from spec.

**Comment by esgomezm** [comment]
Yes!!

**Comment by FynnBe** [comment]
done
