### ISSUE TITLE
Is "outputs" a required field or an optional one?

### ISSUE THREAD

**Issue by mese79** [bioimage-io/spec-bioimage-io#519]
When I try to validate a simple model data with all required fields provided, I get an error due to assumption of **`outputs`** as a list and not taking into account that might be a `None` object:
https://github.com/bioimage-io/spec-bioimage-io/blob/451cf4ece42e26fd14ebb66b8f2877aa1f3854cc/bioimageio/spec/model/v0_4/schema.py#L445  
```python
TypeError: 'NoneType' object is not iterable
```

Sample code:
```python
from bioimageio.spec import model

model_schema = model.schema.Model()
errors = model_schema.validate({
    'name': 'Super Model',
    'description': 'very naive model',
    'license': 'MIT',
    'documentation': '/Users/mehdi/Projects/xxx/README.md',
    'type': 'model',
    'format_version': '0.4.9',
    'timestamp': '2023-06-27T15:55:19.659008',
    'authors': [{'name': 'John Doe'}],
    'weights': {'torchscript': {'source': '/Users/mehdi/Projects/xxx/model.pth'}},
    'test_inputs': ['/Users/mehdi/Projects/xxx/test-input.npy'],
    'inputs': [{'name': 'input_1', 'data_type': 'float32', 'shape': (1, 1, 128, 128), 'axes': 'bzyx'}],
    'test_outputs': ['/Users/mehdi/Projects/xxx/test-output.npy']
})
```

So is the **`outputs`** field required?

**Comment by FynnBe** [comment]
yes, outputs is required. 
I see though that the [documentation](https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/model_spec_0_4.md#outputs) claims that it is optional... I'll keep this issue open while working on general updates that should include this fix.
