### ISSUE TITLE
Define .bioimageio.yaml suffix

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#522]
I have generated a json schema encompassing our whole spec. It is not sufficient to validate, but a great help to edit an rdf.yaml 'intelligently'.

For example with [this YAML vscode extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) 
and configuring our bioimageio schema manually I get
![image](https://github.com/bioimage-io/spec-bioimage-io/assets/15139589/9e3426c7-b6e4-4d75-b523-ba79b5458efc)

and simply expanding `input` yields:
![image](https://github.com/bioimage-io/spec-bioimage-io/assets/15139589/f99fd31a-eb59-40a9-9a23-a5d9d081add1)

To make our schema available per default/give easy access to it to many users it would be great to add it to https://www.schemastore.org/json/

For this we would need a dedicated suffix.
I therefore propose that we accept any file with a `.bioimageio.yaml` suffix as entry point in a model package.
If we do not want to allow multiple resources per package we can also only look for the `rdf.bioimageio.yaml`.
To not break anything we can officially look for the `rdf.yaml` if no `.bioimageio.yaml` file was found. (or in the other order).

The bioimageio json schema draft I have played around with in the screenshots above is here:
[bioimageio_spec_latest.json.txt](https://github.com/bioimage-io/spec-bioimage-io/files/12214369/bioimageio_spec_latest.json.txt)
(note: to upload here in github I added a '.txt' extension)

cc @oeway @esgomezm @constantinpape @carlosuc3m @k-dominik @emilmelnikov

**Comment by FynnBe** [comment]
we could additionally register type specific suffixes, e.g. `.model.bioimageio.yaml`

**Comment by oeway** [comment]
Hi @FynnBe This is great! `.bioimageio.yaml` sounds good! Love it!

**Comment by esgomezm** [comment]
I also think it's nice idea! Yes, thank you Fynn!
