### ISSUE TITLE
Incorporate Processing mode to axes

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#526]
mode fields:
- https://github.com/bioimage-io/spec-bioimage-io/blob/cdec10c2131c949f0bd1a57df894b07fb5959e80/bioimageio/spec/model/v0_5.py#L494
- https://github.com/bioimage-io/spec-bioimage-io/blob/cdec10c2131c949f0bd1a57df894b07fb5959e80/bioimageio/spec/model/v0_5.py#L517

per_sample -> do not reduce batch axis (to compute mean, etc..) -> do not include in `axes`
per_dataset -> reduce batch axis -> include in `axes`

**Comment by ctr26** [comment]
@FynnBe need some advice

**Comment by FynnBe** [comment]
Hey @ctr26 sorry for having kept this issue's description quite brief.

I think we concluded that the `mode` field should be removed and instead `axes` should include the batch axis or not, depending the the mode. 
So we need to 
- [ ] remove `mode` for model v0.5
- [ ] update `axes` description/validation for model v0.5
- [ ] update converter s.t. model v0.4 `mode` is converted to updated `axes` in model v0.5

**Comment by FynnBe** [comment]
implemented in model 0.5
