### ISSUE TITLE
Missing type in the spec

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#538]
For some reason, the key `type` is not listed in the generated markdown file, for both generic RDF and model RDF, e.g.: https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/model_spec_latest.md

@FynnBe

**Comment by FynnBe** [comment]
the new user docs have it: https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/user_docs/model_descr_v0-5.md#type-literalmodel--model
