### ISSUE TITLE
Upgrade `bio-rdf-validator.imjoy.html` to use patched spec

### ISSUE THREAD

**Issue by jmetz** [bioimage-io/spec-bioimage-io#551]
At the moment, this spec validation is failing on models entered on https://bioimageio-uploader.netlify.app/ as a new non-optional and partially read-only `uploader` field has been added. 

AFAIK (right @FynnBe ?) the old spec has been patched to reflect this, so this validator needs to be updated to the patched spec version.

**Comment by FynnBe** [comment]
yeah, the old spec, but not the old spec library 0.4 as we planned to drop support for it (as the new spec library 0.5 is released).
In the meantime you wanted to simply drop the `uploader` to make validation with the old library pass or use the json schema validation instead. has this plan changed?

**Comment by FynnBe** [comment]
oh sorry, just saw this is a rather old issue... I guess this can instead be closed as discussed offline a while back
