### ISSUE TITLE
pretty validation errors does not work

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/spec-bioimage-io#591]
Hi there! 
The following function does not do anything regarding having beautiful errors 

````python
from bioimageio.spec.pretty_validation_errors import (
    enable_pretty_validation_errors_in_ipynb,
)

enable_pretty_validation_errors_in_ipynb()
````
![Screenshot 2024-05-06 at 17 32 09](https://github.com/bioimage-io/spec-bioimage-io/assets/43643518/d426eac6-7c98-406d-ac2c-952c50998e9b)

**Comment by FynnBe** [comment]
there was a bug indeed. the cleaned up stacktrace was appended to the original one instead of replacing it... 
fixed in #605
