### ISSUE TITLE
Example on Description: 5.2 `ParameterizedSize` should be `SizeReference`

### ISSUE THREAD

**Issue by qin-yu** [bioimage-io/spec-bioimage-io#598]
File: [BioImage Model Zoo Example notebook](https://github.com/bioimage-io/spec-bioimage-io/blob/main/example/load_model_and_create_your_own.ipynb)

**Comment by FynnBe** [comment]
yes, correct!

**Comment by qin-yu** [comment]
In 5.4, `torchscript_weights_src` is not defined.

**Comment by qin-yu** [comment]
Hey @FynnBe, instead of fixing all bugs in the existing example, can I just upload a notebook for packaging Cellpose models and a notebook for downloading PlantSeg models? I think these working real world notebooks might be more helpful and these are almost ready to be used as examples/tutorials.

**Comment by FynnBe** [comment]
sure, feel free to open a PR with a new example! 👍

**Comment by FynnBe** [comment]
"`SizeReference` instead of `ParameterizeSize`" and "`torchscript_weights_src` is not defined are fixed in the [current notebook version](https://github.com/bioimage-io/spec-bioimage-io/blob/15ea0f7cb3fe593978d1e73a83de1d4a6e31382a/example/load_model_and_create_your_own.ipynb)
