### ISSUE TITLE
model-test-run

### ISSUE THREAD

**Issue by marcus1337** [bioimage-io/spec-bioimage-io#667]
**Background**
We are working on separating model testing from previously running in GitHub Actions to run on our own servers via k8s.
This is the [repo](https://github.com/aicell-lab/model-test-run/tree/dev) for the model-test-run scripts. It contains a dockerfile for easy deployment to k8s.

**Problem**
Certain bioimageio.spec API calls used to run model testing display unexpected errors.
Example usage: `docker run --rm -it my_container --model="https://uk1s3.embassy.ebi.ac.uk/public-datasets/hiding-tiger.zip"`

It is possible something is wrong with the specific [model](https://uk1s3.embassy.ebi.ac.uk/public-datasets/hiding-tiger.zip) we use for testing.

**Side notes**
This is issue may be modified in the future.

**Comment by oeway** [comment]
Hi @marcus1337 thanks for creating the issue, could you describe the issue what you are facing with loading the model description, and run the models? Maybe this issue should be transferred to the core repo?

Cc @FynnBe

**Comment by marcus1337** [comment]
When passing rdf.yaml from [model](https://uk1s3.embassy.ebi.ac.uk/public-datasets/hiding-tiger.zip) to `validate_format` (`from bioimageio.spec import validate_format`) it fails the validation test. There might be something faulty about `validate_format`, the model, or both.

Debug prints:
```
Testing [https://uk1s3.embassy.ebi.ac.uk/public-datasets/hiding-tiger.zip]
Model downloaded to /tmp/model_projects/hiding-tiger.zip
Model unpacked to /tmp/model_projects/hiding-tiger
zip [/tmp/model_projects/hiding-tiger.zip], unpack [/tmp/model_projects/hiding-tiger]
ValidationResult(success=False, details=
bioimageio format validation failed
format version  | unknown unknown 
bioimageio.spec | 0.5.3.3 
initialized InvalidDescr to describe unknown unknown 
Invalid content of type '<class 'pathlib.PosixPath'>'
```
