### ISSUE TITLE
Discard `source` key in model.yaml and only support serialized models

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#86]
While discussing the `source` key, I am now thinking that maybe we can just remove the `source` code key considering that ilastik is the only tools that uses the source code to construct a model and now you support torchscript and keras. 

Allowing executing scripts provided by the user pose an obvious security risk for the user (although serialized model is still not secured, [note from tensorflow](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md#running-untrusted-models)). 

Plus, in general, serialized model provides better portability (i.e. work with different runtime environment, some of them are faster than the original script framework, [reference](https://towardsdatascience.com/pytorch-jit-and-torchscript-c2a77bac0fff)).

For reproducibility purpose, we already have `git_repo` key for linking full source code. 

We don't need to implement this right now, but I think it would be good discuss different possibilites here.

**Comment by constantinpape** [comment]
As far as I know providing the source code is the only way to serialize the models in  a way that they are still trainable in pytorch. (And we do want to retrain in ilastik!)
Also, torchscript exports may not work reliably for every model.
So I don't think we can get rid of this!

(I do agree though that `source` may not be the best field name, but let's discuss this in the other issue.)

**Comment by FynnBe** [comment]
source code based models also make it easier for model developers to absorb non-standardized pre-/postprocessing.

Any consumer software is free not to support source code based models or at least prefer serialized ones where possible, but I see no convincing argument to remove source code based models from the spec.

**Comment by oeway** [comment]
> As far as I know loading from source is the only way to serialize the models in a way that they are still trainable in pytorch. (And we do want to retrain in ilastik!)
Also, torchscript exports may not work reliably for every model.
So I don't think we can get rid of this!

That's true, for further training in pytorch you will need source. I think that make sense, and I just checked that torch.hub is also using source code: https://pytorch.org/docs/stable/hub.html


> source code based models also make it easier for model developers to absorb non-standardized pre-/postprocessing.

This is also true, but didn't we say we will use `run_model` to address it?

**Comment by constantinpape** [comment]
Ok, let's close this one then.

**Comment by FynnBe** [comment]
> This is also true, but didn't we say we will use run_model to address it?

I don't see how `run_mode` helps with this directly. This may be useful for transforms that a specific consumer software supports, but not any arbitrary transforms included in the forward path of the model....
