### ISSUE TITLE
build_spec support for keras/tf

### ISSUE THREAD

**Issue by maweigert** [bioimage-io/spec-bioimage-io#87]
Hi, 

It appears that [`build_spec`](https://github.com/bioimage-io/python-bioimage-io/blob/7d47a8cdf311348d9ab2ceca13fd925f708c4218/bioimageio/spec/utils/build_spec.py#L215) currently does not support keras.tf `hdf5` weights, minimal example:

```python 
import bioimageio

spec = bioimageio.spec.utils.build_spec(
        model_kwargs={},
        weight_uri='https://github.com/JonathanCMitchell/mobilenet_v2_keras/releases/download/v1.1/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5',
        weight_type='keras_hdf5',
        test_inputs=['https://github.com/bioimage-io/pytorch-bioimage-io/raw/master/specs/models/unet2d_nuclei_broad/test_input.npy'],
        test_outputs=['https://github.com/bioimage-io/pytorch-bioimage-io/raw/master/specs/models/unet2d_nuclei_broad/test_input.npy'],
        name='', description='', authors=[],tags=[], license='', documentation='', covers='', dependencies='',cite=[]
    )
```

```
TypeError: Parameters to generic types must be types. Got 0.
```

**Comment by constantinpape** [comment]
Good point. I didn't add it yet because I didn't have an example at hand when working on this.
I will try to do this later and let you know once it's there.
@oeway @esgomezm , do you have a good example with the keras hdf5 format uploaded somewhere, that I could use for the tests here?

**Comment by esgomezm** [comment]
Hi @constantinpape,

Do you need it in TF1 or TF2? I have some in TF1.15. Also, do you need the weights or the entire model?

**Comment by constantinpape** [comment]
> Do you need it in TF1 or TF2? I have some in TF1.15. Also, do you need the weights or the entire model?

The TF version does not really matter, I just need some example model for the test.
Ideally, I would need a link to a valid model yaml hosted somewhere, like here: https://github.com/bioimage-io/python-bioimage-io/blob/7d47a8cdf311348d9ab2ceca13fd925f708c4218/tests/test_bioimageio/test_spec/test_utils/test_build_spec.py#L51-L52

**Comment by esgomezm** [comment]
Ok, so this model has a keras model inside: https://github.com/deepimagej/models/blob/master/fru-net_sev_segmentation/model.yaml

Let's see if it works!

**Comment by constantinpape** [comment]
Thanks @esgomezm. I am using it for the tests now, but it looks like there are some issues with the model.yaml and it doesn't pass the checks. It would be great if we can fix these issues to make the tests pass.

@maweigert `build_spec` should work for both keras_hdf5 or tensorflow_saved_model_bundle weights now. Also, we just merged all the changes onto master.

**Comment by FynnBe** [comment]
@esgomezm to fix the issues mentioned by @constantinpape I made [this PR](https://github.com/deepimagej/models/pull/22)

**Comment by maweigert** [comment]
Ok, thanks, I'll give it a try later (it appears the whole spec is still developing faster than I can code, so I think I will wait until the dust settles :)

**Comment by constantinpape** [comment]
> (it appears the whole spec is still developing faster than I can code, so I think I will wait until the dust settles :)

Yeah, the python tools are fairly new, so things are changing a bit. I hope it will be more stable in a week or tow ;).
