### ISSUE TITLE
module 'bioimageio.spec.raw_nodes' has no attribute 'BioImageIoManifestModelEntry'

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/spec-bioimage-io#88]
Hi there! 

I'm getting this error when running the bioimageio.spec in the model repo:

https://github.com/deepimagej/models/runs/2741124164

**Comment by constantinpape** [comment]
Thanks for raising this @esgomezm. I have moved it to the spec repository, because we are currently moving the spec validation here, see #80. @FynnBe could you check what's going wrong here?

**Comment by FynnBe** [comment]
I'll finish #80 and then a PR in deepimagej/models... should be fixed today

**Comment by esgomezm** [comment]
Ok! no problem. Whenever you can. Thank you

**Comment by FynnBe** [comment]
fixed in #80
