### ISSUE TITLE
Provide via pip and conda

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#90]
It would be great to provide this as pip and conda pacakge, now that we have merged the python spec functionality:

- [x] make last changes for 0.3.2, see #91
- [x] make a 0.3.2 release to include the new python package
- [x] make a PyPI package (can someone look into this? @FynnBe?)
- [x] make a conda-forge package (I will go ahead and create a PR for this)

**Comment by oeway** [comment]
Just curious about why we need both? Is there any extra benefit by
providing conda package for pure python package?

**Comment by constantinpape** [comment]
> Is there any extra benefit by providing conda package for pure python package?

Yes, it improves dependency handling in conda if it's not necessary to include pip dependencies in the environment.

**Comment by oeway** [comment]
I will work on the pypi packaging as this is required for the packager running in the bioEngine.

**Comment by constantinpape** [comment]
@k-dominik do we have all dependencies on conda-forge now with https://github.com/conda-forge/staged-recipes/pull/15361 merged?

**Comment by oeway** [comment]
All done!
