### ISSUE TITLE
Changes to 0.3.2

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#91]
As discussed in the meeting today.
- Rename `id` to `_id` and treat it as an internal field that should not be provided by users. This is then autogenerated by the website (e.g. by the zenodo upload script).
- make affiliation optional (default: null)
- change default version: null
- Loosen requirements for the `documentation`: we should allow the two following use cases:
    - Having a local .md file, in this case the documentation can be rendered in the bioimage.io card  
    - Having an url in some existing documentation, in this case, the model card should just show something like "The documentation for this model can be found at this link ...".
    
cc @FynnBe @oeway @esgomezm 

Edit: copied the two additional changes on default values from the meeting notes

**Comment by constantinpape** [comment]
@oeway the part of the documentation came up after you left the meeting.
@esgomezm and I think that we should allow linking to external documentation pages in order to avoid duplicate work for models where documentation exists already.

**Comment by oeway** [comment]
> As discussed in the meeting today.
> 
> * Rename `id` to `_id` and treat it as an internal field that should not be provided by users. This is then autogenerated by the website (e.g. by the zenodo upload script).

Good!

> * Loosen requirements for the `documentation`: we should allow the two following use cases:
>   
>   * Having a local .md file, in this case the documentation can be rendered in the bioimage.io card
>   * Having an url in some existing documentation, in this case, the model card should just show something like "The documentation for this model can be found at this link ...".

I would recommend that we enforce a local README file, for a couple of reasons:
 * As a website, we want to keep uses within the website while browsing different models. If each and every model provide a link, the user will need to switch tabs to read them. Which will cause bad experience.
 * External links can break, or from security point of view, we should limit the number of external links.
 * A local document is the best way to guarantee the consistency between the models and the docs. Otherwise, one might have their documentation linked to GitHub README which can be easily updated while the model is frozen.
 * For exported offline packages, it's nice to have a readme file within the package. And a consumer software can easily render a local documentation interface.
 * It is also recommended for many of the archive that to save a README file in the online deposit of dataset.
 * Forcing a local documentation will allow us to tap into the format later, and give better recommendations later for the docs, e.g. implement model cards idea

After all, you can still link to your external documentation within the local README file.

**Comment by constantinpape** [comment]
> After all, you can still link to your external documentation within the local README file.

That is true, although it feels a bit unnecessary to enforce a local file only to provide a link.
And I don't really think that it's good practice to encourage people to duplicate documentation:
In general, writing documentation is not the most liked task, so it will likely be of low quality if another source of documentation already exists.

Anyway, I could live with both solutions here, but we should consider that, I think, many deepimagej models use external documentation already, so we should definitely take @esgomezm opinion into account here.

As an intermediate option, could we implement a conversions from url to local markdown file, which just provides the link, in `maybe_convert`, @FynnBe?

**Comment by FynnBe** [comment]
I still have an (unterstanding) problem with the `_id` field: If we intend to use it only for zenodo uploads and will insert the stable doi from zenodo there, why not use that doi in the first place without inserting it into the model.yaml, in other words why do we have to get it from the model.yaml?
All models hosted on github will not have the private `_id` field inserted and it should still work 'somehow'...?!?

**Comment by FynnBe** [comment]
> As an intermediate option, could we implement a conversions from url to local markdown file, which just provides the link, in `maybe_convert`, @FynnBe?

Yes, if the website actually uses the parsed output generated by python (or serialized again) and not the 'raw' yaml file

**Comment by FynnBe** [comment]
alternatively we could accept a relative .md file path **OR** markdown text, then we would also just render the url...

**Comment by oeway** [comment]
> And I don't really think that it's good practice to encourage people to duplicate documentation:

I think we are encouraging to store the documentation with the model and weights, which is the most sensible thing to do. Why would one want to store their docs elsewhere?  Please note that there is a difference between the documentation for a certain model architecture vs the documentation for a model package. For example, in the documentation in the package, we would like to see how they trained this specific weights. They can always link to the docs of certain consumer software and certain model architecture.

Also consider that after we have the upload interface ready, most users won't need to touch Github at all. They can just be a non-expert user of ilastik/zerocost/ImJoy.  In this case we will perhaps generate the docs directly from a consumer UI.

**Comment by constantinpape** [comment]
> alternatively we could accept a relative .md file path **OR** markdown text, then we would also just render the url...

I like this approach (and we could probably also do the auto-conversion from url to markdown for this option).

**Comment by oeway** [comment]
> Anyway, I could live with both solutions here, but we should consider that, I think, many deepimagej models use external documentation already, so we should definitely take @esgomezm opinion into account here.

@esgomezm What is the case for you to use external links? I found a few examples:
 * [notebook in gist](https://github.com/deepimagej/models/blob/master/skin_lesion_classification/model.yaml#L7): this one is broken already
 * [lab website](https://github.com/deepimagej/models/blob/ab5d5e47f222cd1eca670653a06329f0a580a76c/mt3_virtual_staining/model.yaml#L12)

For It would be much more stable and robust if one can just write a README file locally.

**Comment by oeway** [comment]
> I like this approach (and we could probably also do the auto-conversion from url to markdown for this option).

Do you mean in the upgrade script or you want to do it consistently afterwards? There are other issues with external links, e.g. CORS problem which prevent us from getting the data, the user provided links maybe not "raw",  and not every external link is a markdown file.

**Comment by constantinpape** [comment]
> Do you mean in the upgrade script or you want to do it consistently afterwards? There are other issues with external links, e.g. CORS problem which prevent us from getting the data, the user provided links maybe not "raw", and not every external link is a markdown file.

No, the idea would be that if the autoconversion just takes the url and generates a markdown string like:
`You can find the documentation here <INSERT LINK HERE>`.
The idea here is just to support models in 0.3.0/0.3.1 format that don't have the .md file yet without breaking the CI.

In the future we would then demand that documentation is either a markdown string or a local .md file.

**Comment by oeway** [comment]
> alternatively we could accept a relative .md file path OR markdown text

Sure we can potentially allow that, but adding long markdown text in yaml doesn't look nice itself, and also imagine you have a 500 lines of markdown text, it will basically dominate the entire page of our yamll. It's not absolutely needed, but I think it will be much better if we save it separately as a markdown file. If we call it README.md for example, github will automatically render it when you open the folder.

> No, the idea would be that if the autoconversion just takes the url and generates a markdown string like:
You can find the documentation here <INSERT LINK HERE>.
The idea here is just to support models in 0.3.0/0.3.1 format that don't have the .md file yet without breaking the CI.

I see, sure, but we can also generate a markdown file, save as README.md and insert it as a relative path.

**Comment by FynnBe** [comment]
> Sure we can potentially allow that, but adding long markdown text in yaml doesn't look nice itself, and also imagine you have a 500 lines of markdown text, it will basically dominate the entire page of our yamll. It's not absolutely needed, but I think it will be much better if we save it separately as a markdown file. If we call it README.md for example, github will automatically render it when you open the folder.

we could easily enforce a limit on the length of the plain markdown text, but for visualizing it on the website I don't see the difference if the markdown comes from the yaml or is read from a separate file. the idea was just that "https://example.com" is valid markdown syntax... 
> You can find the documentation here <INSERT LINK HERE>.

I wouldn't even convert and just render on the webiste:
```
documentation:
<either [content from markdown.md] or [plain markdown from yaml that might happen to be a single url]>
```

> I see, sure, but we can also generate a markdown file, save as README.md and insert it as a relative path.

maybe I am missing something, but no one will see that the file is called README.md, right?

**Comment by oeway** [comment]
> I still have an (unterstanding) problem with the _id field: If we intend to use it only for zenodo uploads and will insert the stable doi from zenodo there, why not use that doi in the first place without inserting it into the model.yaml, in other words why do we have to get it from the model.yaml?
All models hosted on github will not have the private _id field inserted and it should still work 'somehow'...?!?

Imagine you downloaded a model from our website as a package, include the id in the packaged yaml will allow us to track it back to the "origin". E.g. when you want to make changes, you can select your local package in the upload interface, we will extract the id and automatically associated with its zenodo deposit. 

This is super helpful to avoid duplications, if you try our upload feature in the preview you will see that each time it will create a new deposite in your zenodo account which you cannot easily remove. Having the capability to keep track of these information would  make it much easier.

Similarly, I will have other info I might want to keep track of for the website, I really don't think we should add these private keys into the spec. I think the best way forward is to just ignore private keys starts with `_` in the validator.  These keys can easily change when we switch to different implementations.

**Comment by oeway** [comment]
> we could easily enforce a limit on the length of the plain markdown text, but for visualizing it on the website I don't see the difference if the markdown comes from the yaml or is read from a separate file. the idea was just that "https://example.com" is valid markdown syntax...

I got this, but it's really bad practice to use "https://example.com" as documentation for a model. It's make sense. We are talking about a set of specific model weights, I don't see why one would build a page on another website to keep track of his model weights. If they just want to add a link to their github source repo or lab web site, they are doing it wrongly. This is exactly what we want to prevent.  The model package documentation should mainly targeted to the current set of weights.

My point here is not about rendering, but rather by forcing a local README file we encourage users to write model+weights specific documentation, not a generic docs for all the models trained with stardist, cellpose, or produced from a lab.

**Comment by constantinpape** [comment]
> I see, sure, but we can also generate a markdown file, save as README.md and insert it as a relative path.

Yes, that also works in case we don't want to allow the markdown strings. 

> We are talking about a set of specific model weights, I don't see why one would build a page on another website or github repo to keep track of a specifically trained model weights.

The thing is that these exact descriptions can exist already, e.g. for stardist: https://github.com/stardist/stardist#pretrained-models-for-2d. And we don't want to force people to duplicate this.

But I would be fine if we restrict it to a local .md file; in case people have some external documentation they can simply put the link inside of the markdown. And for the old models that don't comply we can have the auto conversion as outlined above.

**Comment by FynnBe** [comment]
> My point here is not about rendering, but rather by forcing a local README file we encourage users to write model+weights specific documentation, not a generic docs for all the models trained with stardist, cellpose, or produced from a lab.

That is a good point! Whatever we do, we should encourage model specific documentation in a local markdown file.
But for a very short description that is model specific and links to a more general website for the common part, writing plain markdown into the model yaml might make sense, too. This could be a convenient solution in some cases, that of course can be misused. Bottom line is that we cannot force people to write extensive per model documentation. They'll just put an empty markdown file (or one with a single url) in there and call it a day as well... and then we enforce a certain length and then they just repeat the url... then we detect that and they start adding randomly generated words... 🥇

**Comment by oeway** [comment]
> But for a very short description that is model specific and links to a more general website for the common part, writing plain markdown into the model yaml might make sense, too. This could be a convenient solution in some cases, that of course can be misused. Bottom line is that we cannot force people to write extensive per model documentation. They'll just put an empty markdown file (or one with a single url) in there and call it a day as well... and then we enforce a certain length and then they just repeat the url... then we detect that and they start adding randomly generated words... 🥇

I agree. In the end it's a more like a psychological thing.

An additional point for not saving documentation string in the yaml is we already have `description` key for the short version, so for `documentation` key, we really expect long description in proper format with sections, images in it.

I would also mention that in the `documentation` markdown file, user should use absolute URL, or relative url that point to the files in the same folder (e.g. `./screenshot-2021-1-1.png`, but NOT `../screenshot.png`).

**Comment by constantinpape** [comment]
Ok, after some discussion, I think we have agreed on these changes:
- Remove the `id` field again; it will be stored in a website specific part of `config`. (The change to the jsonschema for the rdf is already done.)
- Keep a strict requirement for documentation in local .md files, but adapt the converter, s.t. we add a markdown with a link for old models that contained a link to some external url instead.
- make affiliation optional (default: null)
- change default version: null

@FynnBe could you plesae implement these changes in the validator?

**Comment by esgomezm** [comment]
Hi there, 

I'm ok with the changes for the fields in the manifest. 

With respect to the documentation, we do not have a strong opinion on that except that there should exist some info. Indeed there are many different nice ways of documenting a model. For example, some people liked much more to see a compiled user-friendly Jupyter notebook than reading documentation. In terms of reproducibility, it's quite optimal. 

It'd be very nice if all the models were super well documented but the main concern is whether it can be an impediment for having some nice contributions. Maybe it is easier to first think about what do we want to ask for and then how we provide that information.

I try to let you some situations we got (sorry for the length):

- Researchers like to have their work centralized, so having additional documentation to their publication, code or webpage is not always something that they'd like to do. A reason sometimes can be: if the bioimage model zoo is self-contained, there could be a risk for not citing the original publication. Also, they many times say: go to the supplementary material.

> We are talking about a set of specific model weights, I don't see why one would build a page on another website or github repo to keep track of a specifically trained model weights. If they just want to add a link to their github source repo or lab web site, they are doing it wrongly. This is exactly what we want to prevent. The model package documentation should mainly targeted to the current set of weights. For github repo, they can use git_repo key and for lab website, they can add an acknowledgement section in the documentation.

Indeed we should consider that many researchers will not only post their models in the BioImage Model Zoo. At least at the very beginning. Some publishers ask you to provide all the material from the editorial's site. It happens the same for the models from challenges. They are already at the challenge page, properly documented. Why should they duplicate the effort? 

- Some researchers complained about the lack of that information because the model could be misused: information about the training data or any key aspect when using the model, is crucial, although I do not see why this cannot go into the description or linked to datasets. Do you also want to specify training parameters, learning curves, and so on? 

- Is this documentation different for models that are already ready to use (let's say they are quite general) and the models that are thought for fine-tuning? For example, the pre-trained models of the TF API or the ones that used to be in the Model Zoo, do they have such documentation?

**Comment by FynnBe** [comment]
Requiring a local markdown file for documentation leaves a lot of room on how to fill that file with any valid markdown. Narrowing down the syntax is helpful for rendering it on our website and also for showing the documentation in any consumer software.
I hope it will be used to write a concise model instance/weights specific documentation and add links to centralized more general and more extensive documentation (or non-bioimageio jupyter notebooks, etc...). 
Anyhow, I suggest we go ahead with the local markdown file for now and see if we can improve this at a later stage when more examples are in use.

**Comment by constantinpape** [comment]
@esgomezm thanks for listing all the use cases in so much detail!
I think we should try to compress this into the docu pages at some point. In any case, if there exists extensive documentation for a model already, the corresponding link(s) can always be put into the markdown file, so I don't think that we put a too large burden on model developers by requiring this.

So I think we are all in agreement and can go ahead with this.

**Comment by oeway** [comment]
This should be done already.
