### ISSUE TITLE
Invalid value for output name field on validation

### ISSUE THREAD

**Issue by tomburke-rse** [bioimage-io/spec-bioimage-io#92]
Hi all,
I'm currently updating the N2V model and noticed a problem with the validation.

This is the error I am getting
`python -m pybio.spec verify-spec .\model.yaml
{'outputs': {0: {'name': ['Invalid input.']}}}`

This is the model file. Adding '' to the output name does not help.
`outputs:
- name: activation_11/Identity
  axes: byxc
  data_type: float32
  data_range: [-inf, inf]
  halo: [0, 22, 22, 0]
  shape:
    offset: [0, 0, 0, 0]
    scale: [1.0, 1.0, 1.0, 1.0]
    reference_input: input
  postprocessing:
  - name: scale_linear
    kwargs:
      axes: yxc
      gain: [15374.962]
      offset: [47944.324]`

**Comment by constantinpape** [comment]
I have transferred the issue because it relates to the validation that was moved here.

**Comment by FynnBe** [comment]
I suppose it is resolved, please reopen if needed.
