### ISSUE TITLE
Private _id field

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#94]
Moving the discussion about the `_id` field from #91 to a separate issue. Quoting https://github.com/bioimage-io/spec-bioimage-io/issues/91#issuecomment-854836793:

> I still have an (unterstanding) problem with the _id field: If we intend to use it only for zenodo uploads and will insert the stable doi from zenodo there, why not use that doi in the first place without inserting it into the model.yaml, in other words why do we have to get it from the model.yaml?
> All models hosted on github will not have the private _id field inserted and it should still work 'somehow'...?!?

**Comment by constantinpape** [comment]
@FynnBe: my understanding is that all models would eventually need the `_id` field. For the models that are on gitub we could hopefully write a bot that makes a PR to add the id as soon as a model is listed in a manifest that is index by bioimage.io.
Probably @oeway has more thoughts on this matter.

**Comment by FynnBe** [comment]
Why not have one central file in bioimage-io/bioimage.io that keeps track of all ids then? saved the dois for zenodo, some clever github derived id for the those joining via a github manifest...
Wouldn't that be a cleaner separation of database and entries in the database? @fjug was just so convincing before he changed his mind on the matter... ^^

**Comment by oeway** [comment]
> Why not have one central file in bioimage-io/bioimage.io that keeps track of all ids then? saved the dois for zenodo, some clever github derived id for the those joining via a github manifest...
Wouldn't that be a cleaner separation of database and entries in the database? @fjug was just so convincing before he changed his mind on the matter... ^^

See here: https://github.com/bioimage-io/spec-bioimage-io/issues/91#issuecomment-854870918

Off the topic thing is: when I read a bit more about web3 and IPFS, I started to think centralised stuff are actual more fragile.


Regarding the private _id field:
I am now thinking that we should not include any private field in the spec itself. We don't need to, it's better to focus our energy on fields that matters for the model itself. The private field is just our implementation details. 

I can potentially use a different file for this purpose, but it will just make the files more concise if we allow `_` private field in the RDF yaml. Alternatively we can also have a `config` key in the general RDF, so we can add the _id and any key there too. This is perhaps a even better solution, no?

**Comment by FynnBe** [comment]
for my general understanding: we want `id` to keep track of a model and differentiate updates from new submissions. Anything else?

How about adding a `parents` field with a list of doi/zenodo/github urls, of the published model and always append on package download... on upload the last parent can be compared with the upload and then we can decide if we want to update or "go to the next generation".
Of course people could add parents manually, which would be meaningful, and we can enforce that a parent url is either a doi url or a github link with hash (no branch, etc., so it's also reasonably stable; I mean if that github link doesn't exist anymore we have lost the model, and it's id won't help us either)?

**Comment by oeway** [comment]
> for my general understanding: we want id to keep track of a model and differentiate updates from new submissions. Anything else?

Yes, and we also refer it within links.


> How about adding a parents field with a list of doi/zenodo/github urls, of the published model and always append on package download... on upload the last parent can be compared with the upload and then we can decide if we want to update or "go to the next generation".
Of course people could add parents manually, which would be meaningful, and we can enforce that a parent url is either a doi url or a github link with hash (no branch, etc., so it's also reasonably stable; I mean if that github link doesn't exist anymore we have lost the model, and it's id won't help us either)?

I might get it wrong, but isn't the `parents` field same as `id` except it allows multiple values? Semantically, not sure if you download a file from an url, you create a child. They just copies of the same thing, right? 

I see pros and cons with different options, hard to choose without actually try it. Therefore, I would suggest we don't waste time here to discuss, but rather make it `config` or `private`, we implement it and use it "off the spec", then see how it works. If necessary we take it as part of the spec.

**Comment by constantinpape** [comment]
> I can potentially use a different file for this purpose, but it will just make the files more concise if we allow `_` private field in the RDF yaml. Alternatively we can also have a `config` key in the general RDF, so we can add the _id and any key there too. This is perhaps a even better solution, no?

Yes, I really like that approach, because we don't enforce any validation in config rn anyway, so you could just add
```yaml
config:
  bioimageio:
    id: 1234567
    ...
```
to keep track of anything specific to the website.

And adding `config` to the rdf might be a good idea in general, so that people can save other custom fields for their datasets or notebooks.

**Comment by constantinpape** [comment]
I made #95 for introducing `config` in the rdf.

**Comment by constantinpape** [comment]
Ok, I think we can consider this as being solved for now and I will close this. Feel free to reopen if we need more discussion.
