### ISSUE TITLE
Disallow subfolders in the model package

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#96]
We didn't specify how the model package should behave when it comes to subfolders. Since Zenodo does not allow folders, and also in general it's easier to just do a plain folder of files without subfolders in the model package.

I hereby propose that we write in the spec that a model package must not contain any subfolder. If necessary, they can use zip files in side the model pacakge, same as we did with the deepimagej model weights.

**Comment by oeway** [comment]
Update: although zenodo does not allow subfolders, but it allows `/` in the file name, this will allows us implementing virtual folders. We need to implement this in the packagers.

Basically we need to download the file and check whether its file name contains `/`. If yes, we place it under the corresponding folder structure.
- [ ] implement this in python packager @FynnBe 
- [ ] implement this in js packager @oeway 


So maybe we can allow subfolders, but definitely not allow to refer to parent folder.

**Comment by FynnBe** [comment]
`/` in the file name sounds very error-prone.. could we not just keep it flat and substitute `/` with `_`?

**Comment by constantinpape** [comment]
> `/` in the file name sounds very error-prone.. could we not just keep it flat and substitute `/` with `_`?

I would also be in favor of keeping it flat.

**Comment by FynnBe** [comment]
just tested uploading a nested zip to zenodo... 
did you already implement it in the js packager, @oeway ?
![image](https://user-images.githubusercontent.com/15139589/127996116-4db555bf-7151-41cd-9b2d-8334ae95935b.png)
(it's the 'nested/folder/README.md')

**Comment by FynnBe** [comment]
btw, a click on the "Download RDF Package" link
![image](https://user-images.githubusercontent.com/15139589/127996367-8e18e518-be8c-46c5-b478-ce6514dc6aed.png)
gives me 
![image](https://user-images.githubusercontent.com/15139589/127996398-0645d43e-e165-4636-ae4a-0d12046c6c93.png)
That's by design, right? What needs to happen for it to work? could we add that in the 'error' message?

**Comment by FynnBe** [comment]
fyi: the uploaded test package is broken...

**Comment by oeway** [comment]
> `/` in the file name sounds very error-prone.. could we not just keep it flat and substitute `/` with `_`?

Technically, that's not a file name, it's a key or a path, it's common for s3-like storage systems and it allows supporting virtual folders.

This means it will have no impact on our spec at all, it only affect how we download and upload from zenodo.

It won't matter much for model packages if we only allow flat folder structure, but it will make a difference for dataset pacakage for example, we can then support zarr directory store stored in a subfolder.
 

> That's by design, right? What needs to happen for it to work? could we add that in the 'error' message?

Currently, that link will only work if we approve it to be part of bioimage.io, I assume your new model is not approved yet, right? We can perhaps also support the link even if it's approved yet, but we might want to show a warning to the user that this package is not approved yet.

**Comment by FynnBe** [comment]
When trying to update my test entry (https://sandbox.zenodo.org/record/892181#.YQkSlo5MFjG)
I cannot edit the 'documentation' field.... Is this a bug or just a missing feature?

**Comment by FynnBe** [comment]
ah, I suppose I could in 'Review & Upload'... yeah that's fine! 👍

**Comment by FynnBe** [comment]
alright, with some fixes it works:
```
>>> raw_model = spec.load_raw_resource_description("https://sandbox.zenodo.org/record/892199/files/rdf.yaml")
>>> raw_model.documentation
URI(scheme='https', authority='sandbox.zenodo.org', path='/record/892199/files/nested/folder/README.md', query='', fragment='')
>>> model = spec.load_resource_description("https://sandbox.zenodo.org/record/892199/files/rdf.yaml")
>>> model.documentation
WindowsPath('C:/Users/fbeut/AppData/Local/Temp/bioimageio_cache/https/sandbox.zenodo.org/record/892199/files/nested/folder/README.md')

```

**Comment by FynnBe** [comment]
> Currently, that link will only work if we approve it to be part of bioimage.io, I assume your new model is not approved yet, right? We can perhaps also support the link even if it's approved yet, but we might want to show a warning to the user that this package is not approved yet.

Maybe we can just mention that in the 'oops: resource not found' pop-up...

**Comment by constantinpape** [comment]
> fyi: the uploaded test package is broken...

Which one is that?

**Comment by FynnBe** [comment]
> Which one is that?

This one:
> When trying to update my test entry (https://sandbox.zenodo.org/record/892181#.YQkSlo5MFjG)

whereas this (uglily just reuploaded and not updated) one works: https://sandbox.zenodo.org/record/892199

**Comment by FynnBe** [comment]
One cannot even delete from sandbox.zenodo, huh?

**Comment by oeway** [comment]
> One cannot even delete from sandbox.zenodo, huh?

No, you have to forget about it after publish on sandbox zenodo.


> whereas this (uglily just reuploaded and not updated) one works: https://sandbox.zenodo.org/record/892199

Is this a bug of the bioimage.io?

**Comment by FynnBe** [comment]
> Is this a bug of the bioimage.io?

not necessarily. the `documentation` field cannot be changed in the json schema interface of the upload page and only in the following 'Review & Upload' step. I just realized this right after republishing the test model... 

I suppose it would be nice if the first upload page would already give you somehow the possibility to select a documentation file and not just allow you to upload any files and then add them manually to the yaml in the next step...
